### ISSUE TITLE
Query with "<" 

### ISSUE THREAD

**Issue by fa-ro** [plomino/Plomino#128]
With this query
query = {'Form': 'frmAtto', 'finepubblicazione': '2012/07/15'}
I can find the docs with finepubblicazione=2012/07/15.

How can I query for docs with finepubblicazione<2012/07/15 ?

**Comment by lucamancini** [comment]
Hi all!
I'd like to use a search form to return documents in a range of dates.
I have a "opening_date" in my docs and I'd like to use 'date_min' and 'date_max' to add to my search form for defining the range.
How could I use the search formula?

**Comment by lucamancini** [comment]
[](https://github.com/plomino/Plomino/issues/853)

**Comment by lucamancini** [comment]
[https://github.com/plomino/Plomino/issues/853](url)
