### ISSUE TITLE
Preventing doc editing

### ISSUE THREAD

**Issue by fa-ro** [plomino/Plomino#132]
I have this need:
documents created by user "editor" have to be read-only for everybody, even for the user who created it.
To  accomplish this, I entered a validation formula based on isNewDocument in a field:
if plominoDocument.isNewDocument:
   return ''
else:
  return 'The doc cannot be modified after creation'

This approach doesn't work (plomino get stucked); using isEditMode() doesn't work either (see video http://youtu.be/u5KZj-PLLpQ)

**Comment by ermancio** [comment]
One question: I need to import some data in a form from a csv, I'll insert an hidden field (called Author) from the csv. So I want only my member has able to edit the document inserting the remaining information. I would like to use Plomino_Authors field that contains only the manager name.
How can i add to plomino_authors member during import operation?
Thanks

**Comment by ebrehault** [comment]
Plomino_Authors is a list, so it cannot be directly imported from a CSV file (if a column contains something like `["Eric"]` it will be imported as a text value `'["Eric"]'` and not a list `["Eric"]`).
So you need to create a post import agent that will convert it properly.
Define a separator (for instance #, so the CSV column will contain: Eric#Mary#Rafael) and then in your agent:
```
db = context.getParentDatabase()
for doc in db.getAllDocuments():
    authors = doc.getItem("Plomino_Authors", [])
    if hasattr(authors, 'split'): # it is a string
        doc.setItem("Plomino_Authors", authors.split('#'))
    doc.save()
```

**Comment by ermancio** [comment]
thank you. I'll try to do it

**Comment by djay** [comment]
Alternatively you could write your own CSV import script. Then you aren't
double writing to the db. This is what we normally do. To that you would
need yo whitelist csv as a safe function however.

Perhaps there could be a way to have a presave formulae run in CSV import
Eric? Or some switch to enable normal field formulas on CSV import? Then
you could create a special field for import purposes only

**Comment by ebrehault** [comment]
@djay yes we could add a `onImportDocument` event on PlominoView that will be called for each imported doc.
That's quite easy to implement I think.

**Comment by ermancio** [comment]
Hi Eric.
In plomino_authors the results is [u'_author name_].
And obviously it doesn't work.

**Comment by ebrehault** [comment]
ok, well, write a small agent as indicated to fix this field
