### ISSUE TITLE
Datagrid popup sizing

### ISSUE THREAD

**Issue by lucamancini** [plomino/Plomino#582]
Hi,
I'd like to set width for my datagrid popup.
Its visualization initially requires a manual resize and I need width: 900px.
Is it a matter of css or what else?

Luca

**Comment by ermancio** [comment]
Hi Eric.
I tried to set plominoDialogOptions in datagrid settings but it doesn't work.
I use Plomino 1.15

**Comment by ebrehault** [comment]
Hi,

Plomino 1.15 does not provide this feature.

**Comment by ermancio** [comment]
So there's no way to solve the bug...

**Comment by ermancio** [comment]
I tried to inspect the datagrid popup via firebug and setting diplay: inline-table It works.
But I can't find the related css file.
Can you help me?
L.

**Comment by ermancio** [comment]
Anyway we edited jquery.ui.dialog.min.js in ..\eggs\collective.js.jqueryui-1.8.16.9-py2.6.egg\collective\js\jqueryui\js, setting "heigth = 800px". In this way all our dialogs are ok.
In your opinion, could these settings impact on other dialogs?
L.

**Comment by ebrehault** [comment]
Changing directly the code in collective.js.jqueryui might impact other components in your website using JQueryUI dialogs.
The best solution is just to upgrade to a more recent Plomino version.
