### ISSUE TITLE
Configuration forms (and documents)

### ISSUE THREAD

**Issue by sudhan77** [plomino/Plomino#592]
Hi,
I am trying to set up a Configuration form to pick a selection List. I am using the example given under the How To section on the site. However seem to be getting stuck. If anyone can help me basis the following traceback

Traceback (innermost last):

Module ZPublisher.Publish, line 60, in publish
Module ZPublisher.mapply, line 77, in mapply
Module ZPublisher.Publish, line 46, in call_object
Module Shared.DC.Scripts.Bindings, line 322, in __call__
Module Products.PloneHotfix20130618.spamProtect, line 35, in _patched_bindAndExec
Module Shared.DC.Scripts.Bindings, line 359, in _bindAndExec
Module Products.CMFCore.FSPageTemplate, line 237, in _exec
Module Products.CMFCore.FSPageTemplate, line 177, in pt_render
Module Products.PageTemplates.PageTemplate, line 79, in pt_render
Module zope.pagetemplate.pagetemplate, line 132, in pt_render
Module zope.pagetemplate.pagetemplate, line 240, in __call__
Module zope.tal.talinterpreter, line 271, in __call__
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 888, in do_useMacro
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 954, in do_defineSlot
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 858, in do_defineMacro
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 954, in do_defineSlot
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 946, in do_defineSlot
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 858, in do_defineMacro
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 852, in do_condition
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 852, in do_condition
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 742, in do_insertStructure_tal
Module Products.PageTemplates.Expressions, line 218, in evaluateStructure
Module zope.tales.tales, line 696, in evaluate
URL: file:c:\plone43\eggs\products.cmfplomino-1.19-py2.6.egg\Products\CMFPlomino\skins\cmfplomino_templates\OpenForm.pt
Line 161, Column 24
Expression: <PythonExpr here.openBlankForm(request)>
Names:
{'container': <PlominoForm at /MitMit/mitmit_app/TestforConfiguration>,
 'context': <PlominoForm at /MitMit/mitmit_app/TestforConfiguration>,
 'default': <object object at 0x0066E830>,
 'here': <PlominoForm at /MitMit/mitmit_app/TestforConfiguration>,
 'loop': {},
 'nothing': None,
 'options': {'args': ()},
 'repeat': <Products.PageTemplates.Expressions.SafeMapping object at 0x08DF8330>,
 'request': <HTTPRequest, URL=http://localhost:8080/MitMit/mitmit_app/TestforConfiguration/OpenForm>,
 'root': <Application at >,
 'template': <FSPageTemplate at /MitMit/mitmit_app/TestforConfiguration/OpenForm>,
 'traverse_subpath': [],
 'user': <PropertiedUser 'admin'>}
Module Products.PageTemplates.ZRPythonExpr, line 48, in __call__
__traceback_info__: here.openBlankForm(request)
Module PythonExpr, line 1, in <expression>
Module Products.CMFPlomino.PlominoForm, line 1024, in openBlankForm
Module Products.CMFPlomino, line 167, in newf
Module Products.CMFPlomino.PlominoForm, line 679, in displayDocument
Module Products.CMFPlomino, line 167, in newf
Module Products.CMFPlomino.PlominoField, line 282, in getFieldRender
Module Products.CMFPlomino.fields.selection, line 110, in getSelectionList
TypeError: 'NoneType' object is not iterable

**Comment by ebrehault** [comment]
Apparently there is no value defined for your selection list.
What did you entered in the Settings tab?

**Comment by ebrehault** [comment]
ok and what is the formula of your JobsIndustry field ?

**Comment by sudhan77** [comment]
field type selection list

formula

db = plominoDocument.getParentDatabase()
config = db.getDocument('configuration')
available_types = config.getItem('JobsIndustry')




Selection List Formula

#Plomino import libConfig
db = plominoContext.getParentDatabase()
config = db.getDocument('configuration')
frmConfig = db.getForm('frmConfiguration')
separator = '|'
return libConfig_getSelectionList('JobsIndustry')

**Comment by ebrehault** [comment]
Actually I do not understand how it is supposed to work, I made a similar mechanism for Config doc, but it is not exactly the same, and here I am lost. This How To has been written by Jean Jordaan. @jean could you explain us?

**Comment by jean** [comment]
The idea is as follows:
- you have e.g. `frmConfiguration/default_room_types` (selection list; *Selection list formula*: `return ['Single room|single', 'Double room|double']`)
- in an application form, you want to allow a choice, so you create e.g. `frmBooking/room_type` (selection list; *Selection list formula*: `#Plomino import libConfig
return libConfig_getSelectionList('default_room_types')`).

So you can have `frmBooking/room_type`, `frmAgentBooking/room_type`, `frmRoom/room_type` that all share the selection list from the *config form*. This accomplishes two things:
- no need to duplicate the selection list formula from field to field;
- no need to create a configuration document using `frmConfiguration`, so no re-saving the form when the default selection list changes. Maintain only the formula on the config form.

@sudhan77 do you have a selection list formula on the config form? If you follow the steps in the howto correctly, it works. You have some unrelated error somewhere.
