### ISSUE TITLE
AttributeError in Auto-increment chrono

### ISSUE THREAD

**Issue by sudhan77** [plomino/Plomino#593]
i am trying to use the example given in How to but i get the following error

line 12, in field_-_ListingForm_-_ReferenceID_-_formula 
AttributeError: setItem 
Context is <PlominoForm> /MitMit/mitmit_app/ListingForm
6: db=plominoDocument.getParentDatabase()
7: searchchrono=db.getIndex().dbsearch({"Form":"frmChrono"})
8: chronodoc=searchchrono[0]
9: currentvalue=chronodoc.chrono
10: newvalue=currentvalue+1
11: # store back the new chrono in the chrono doc 
12: chronodoc.setItem("chrono",newvalue)
13: # return the reference id properly formatted
14: return "JOB NO- %09d" %newvalue

**Comment by ebrehault** [comment]
`dbsearch` returns brains not actual objects (for performance reasons), so `chronodoc` is not a PlominoDocument (hence the setItem method is not defined).
You should do:
`chronodoc=searchchrono[0].getObject()`

**Comment by sudhan77** [comment]
thanks

On Tue, Jan 6, 2015 at 1:51 PM, Eric BREHAULT <notifications@github.com>
wrote:

> dbsearch returns brains not actual objects (for performance reasons), so
> chronodoc is not a PlominoDocument (hence the setItem method is not
> defined).
> You should do:
> chronodoc=searchchrono[0].getObject()
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plomino/Plomino/issues/593#issuecomment-68838087>.
>



-- 
Sudhanshu
