### ISSUE TITLE
ajax and jquery overlay and formhandling tools

### ISSUE THREAD

**Issue by sudhan77** [plomino/Plomino#601]
can we use ajax or jquery overlay and form handling tools in plomino. There is no documentation for the same. I have been trying to implement as per documentation in plone but do not have any success.
pls clarify. 
Case: suppose there are 2 forms - form 1 and form 2. In form 1, I want to provide a link for form 2. If form 2 can open as a popup in ajax or iframe, then the user fills data and submit the form. some variable / variables from this form 2 is required to be used in form 1.

**Comment by ebrehault** [comment]
You can create a computed for display rich text field and insert any Javascript code you want.
In this article, you will find such a field (at the end): http://www.plomino.net/how-to/dynamic-search-results-with-jquery 

But in your case I think you will be probably interested by the builtin Datagrid field. See this sample http://www.plomino.net/samples/datagrids (login demouser/demouser)
