### ISSUE TITLE
plomino element portlet

### ISSUE THREAD

**Issue by sudhan77** [plomino/Plomino#602]
i have a plomino database for a part of my plone site. I want to use plomino element portlet in the front page of the plone site. however the portlet does not work and shows error. how do i diagnose it. where do i exactly check for the database path. is there any other tutorial you could help me with

**Comment by ebrehault** [comment]
2 possibilities:
- the path is wrong: the path should be valid from the current location (in your case, the front page)
- there is a Plomino formula error: just enable the debug mode in your db, and check the server log to see the error

**Comment by sudhan77** [comment]
Thanks, one of the error log is as below, pls let me know if you can find
some hints. Else, I am trying to do some debugging.

Time2015/03/22 11:50:20.047878 GMT-4User Name (User Id)siteadmin
(siteadmin)Request
URLhttp://www.kousalam.com/front-page/document_viewException Type
LocationErrorException
Value(<Products.CMFPlomino.browser.portlet.ElementPortletRenderer
object at 0x7f2d4ca1b750>, 'header')

Traceback (innermost last):

   - Module Products.PloneFormGen.patches, line 21, in safe_render
   - Module Products.Five.browser.pagetemplatefile, line 125, in __call__
   - Module Products.Five.browser.pagetemplatefile, line 59, in __call__
   - Module zope.pagetemplate.pagetemplate, line 132, in pt_render
   - Module zope.pagetemplate.pagetemplate, line 240, in __call__
   - Module zope.tal.talinterpreter, line 271, in __call__
   - Module zope.tal.talinterpreter, line 343, in interpret
   - Module zope.tal.talinterpreter, line 583, in do_setLocal_tal
   - Module zope.tales.tales, line 696, in evaluate
   *URL:
   /usr/local/Plone/buildout-cache/eggs/Products.CMFPlomino-1.19.3-py2.7.egg/Products/CMFPlomino/browser/element_portlet.pt
   <http://element_portlet.pt>*
   *Line 1, Column 0*
   *Expression: <PathExpr standard:u'view/header'>*
   *Names:*

   {'args': (),
    'container': <ATDocument at /kousalam/front-page>,
    'context': <ATDocument at /kousalam/front-page>,
    'default': <object object at 0x7f2d62bc04f0>,
    'here': <ATDocument at /kousalam/front-page>,
    'loop': {},
    'nothing': None,
    'options': {},
    'repeat': <Products.PageTemplates.Expressions.SafeMapping object
at 0x7f2d4cafa940>,
    'request': <HTTPRequest,
URL=http://www.kousalam.com/front-page/document_view>,
    'root': <Application at >,
    'template':
<Products.Five.browser.pagetemplatefile.ViewPageTemplateFile object at
0x7f2d547ed190>,
    'traverse_subpath': [],
    'user': <PloneUser 'siteadmin'>,
    'view': <Products.CMFPlomino.browser.portlet.ElementPortletRenderer
object at 0x7f2d4ca1b750>,
    'views': <Products.Five.browser.pagetemplatefile.ViewMapper object
at 0x7f2d4cac83d0>}

   - Module zope.tales.expressions, line 217, in __call__
   - Module Products.PageTemplates.Expressions, line 147, in _eval
   - Module zope.tales.expressions, line 124, in _eval
   - Module Products.PageTemplates.Expressions, line 97, in
   trustedBoboAwareZopeTraverse
   - Module zope.traversing.adapters, line 136, in traversePathElement
   __traceback_info__:
   (<Products.CMFPlomino.browser.portlet.ElementPortletRenderer object at
   0x7f2d4ca1b750>, 'header')
   - Module zope.traversing.adapters, line 50, in traverse
   __traceback_info__:
   (<Products.CMFPlomino.browser.portlet.ElementPortletRenderer object at
   0x7f2d4ca1b750>, 'header', [])

LocationError: (<Products.CMFPlomino.browser.portlet.ElementPortletRenderer
object at 0x7f2d4ca1b750>, 'header')

Display traceback as text
<http://128.199.230.56:8080/kousalam/error_log/getLogEntryAsText?id=1427039420.050.492664405884>

REQUESTformcookies__ac
'0u46nRe6mOsLpSGr6ypMIWF/CrDKTbpbyjtGKmEywK01NTBlZTJkMHNpdGVhZG1pbiE='lazy
itemsSESSION<bound method SessionDataManager.getSessionData of
<SessionDataManager at /session_data_manager>>otherVIRTUAL_URL_PARTS('
http://www.kousalam.com', 'front-page')VIRTUAL_URL'
http://www.kousalam.com/front-page'__ac
'0u46nRe6mOsLpSGr6ypMIWF/CrDKTbpbyjtGKmEywK01NTBlZTJkMHNpdGVhZG1pbiE='URL0'
http://www.kousalam.com/front-page/document_view'URL2'
http://www.kousalam.com'_plone_ec_cache{139832537399856:
<Products.PageTemplates.Expressions.ZopeContext object at 0x7f2d4e014450>,
139832538719648: <Products.PageTemplates.Expressions.ZopeContext object at
0x7f2d4cac8fd0>}AUTHENTICATION_PATH'kousalam/virtual_hosting//'_oai_cache{139832537399856:
<Products.CMFCore.ActionInformation.oai instance at 0x7f2d4e71fe60>}LANGUAGE
u'en'AUTHENTICATED_USER<PloneUser 'siteadmin'>SERVER_URL'
http://www.kousalam.com'traverse_subpath[]method'GET'ACTUAL_URL'
http://www.kousalam.com/front-page'URL'
http://www.kousalam.com/front-page/document_view'PUBLISHED<FSPageTemplate
at /kousalam/document_view used for /kousalam/front-page>
TraversalRequestNameStack[]VirtualRootPhysicalPath('', 'kousalam')
LANGUAGE_TOOL<Products.PloneLanguageTool.LanguageTool.LanguageBinding
instance at 0x7f2d4cb378c0>BASE0'http://www.kousalam.com'BASE1'
http://www.kousalam.com'BASE2'http://www.kousalam.com/front-page'BASE3'
http://www.kousalam.com/front-page/document_view'URL1'
http://www.kousalam.com/front-page'URL0
http://www.kousalam.com/front-page/document_viewURL1
http://www.kousalam.com/front-pageURL2http://www.kousalam.comBASE0
http://www.kousalam.comBASE1http://www.kousalam.comBASE2
http://www.kousalam.com/front-pageBASE3
http://www.kousalam.com/front-page/document_viewenvironCONNECTION_TYPE
'close'HTTP_ACCEPT
'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8'
HTTP_USER_AGENT'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML,
like Gecko) Chrome/41.0.2272.101 Safari/537.36'HTTP_REFERER'
http://www.kousalam.com/front-page/@@manage-portlets'SERVER_NAME'
kousalam.com'GATEWAY_INTERFACE'CGI/1.1'channel.creation_time1427039419
SERVER_SOFTWARE'Zope/(2.13.22, python 2.7.6, linux2) ZServer/1.1'REMOTE_ADDR
'127.0.0.1'HTTP_ACCEPT_LANGUAGE'en-US,en;q=0.8'SCRIPT_NAME''REQUEST_METHOD
'GET'HTTP_HOST'localhost:8080'PATH_INFO'/VirtualHostBase/http/
www.kousalam.com:80/kousalam/VirtualHostRoot/front-page'SERVER_PORT'8080'
SERVER_PROTOCOL'HTTP/1.0'QUERY_STRING''HTTP_CACHE_CONTROL'max-age=0'
HTTP_ACCEPT_ENCODING'gzip, deflate, sdch'HTTP_COOKIE
'__ac="0u46nRe6mOsLpSGr6ypMIWF/CrDKTbpbyjtGKmEywK01NTBlZTJkMHNpdGVhZG1pbiE%3D"'
PATH_TRANSLATED'/VirtualHostBase/http/
www.kousalam.com:80/kousalam/VirtualHostRoot/front-page'

On Sun, Mar 22, 2015 at 7:59 PM, Eric BREHAULT <notifications@github.com>
wrote:

> 2 possibilities:
>
>    - the path is wrong: the path should be valid from the current
>    location (in your case, the front page)
>    - there is a Plomino formula error: just enable the debug mode in your
>    db, and check the server log to see the error
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plomino/Plomino/issues/602#issuecomment-84617817>.
>



-- 
Sudhanshu

**Comment by ebrehault** [comment]
You have traverse error, so the problem comes from the database path.
Is your db named 'header' ? (apparently that's what it is try to traverse to)

**Comment by sudhan77** [comment]
the plomino database is named mitmit_app. its title is MitMit Jobs &
Internships

On Sun, Mar 22, 2015 at 9:41 PM, Eric BREHAULT <notifications@github.com>
wrote:

> You have traverse error, so the problem comes from the database path.
> Is your db named 'header' ? (apparently that's what it is try to traverse
> to)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plomino/Plomino/issues/602#issuecomment-84644606>.
>



-- 
Sudhanshu

**Comment by ebrehault** [comment]
so the path should be mitmit_app (and not header, header is probably the element id, right?)

**Comment by sudhan77** [comment]
there are 2 portlets i am working on. one is dynamicSearch and other is
CategoryListingHeadlines.

To give a history, i copied this database from my desktop and imported it
into production plone on ubuntu cloud. i think the main issue is the
database is not refreshed. hence the other issue i had raised about the
forms  not being there and the refresh is interrupted midway

On Sun, Mar 22, 2015 at 10:10 PM, Eric BREHAULT <notifications@github.com>
wrote:

> so the path should be mitmit_app (and not header, header is probably the
> element id, right?)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plomino/Plomino/issues/602#issuecomment-84651452>.
>



-- 
Sudhanshu

**Comment by sudhan77** [comment]
Dear Eric
Any suggestions to get the portlets going. I have been able to sort the
database refresh issue
Sudhanshu

On Sun, Mar 22, 2015 at 10:24 PM, Sudhanshu Sekhar Pani <sudhan77@gmail.com>
wrote:

> there are 2 portlets i am working on. one is dynamicSearch and other is
> CategoryListingHeadlines.
>
> To give a history, i copied this database from my desktop and imported it
> into production plone on ubuntu cloud. i think the main issue is the
> database is not refreshed. hence the other issue i had raised about the
> forms  not being there and the refresh is interrupted midway
>
> On Sun, Mar 22, 2015 at 10:10 PM, Eric BREHAULT <notifications@github.com>
> wrote:
>
>> so the path should be mitmit_app (and not header, header is probably the
>> element id, right?)
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/plomino/Plomino/issues/602#issuecomment-84651452>.
>>
>
>
>
> --
> Sudhanshu
>



-- 
Sudhanshu

**Comment by ebrehault** [comment]
In your portlet, you are supposed to show a form.
Does this form work fine when you open it directly ?

**Comment by sudhan77** [comment]
Yes the form and view both are working.

On 3/24/15, Eric BREHAULT <notifications@github.com> wrote:
> In your portlet, you are supposed to show a form.
> Does this form work fine when you open it directly ?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/plomino/Plomino/issues/602#issuecomment-85415604


-- 
Sudhanshu

**Comment by sudhan77** [comment]
Dear Eric
I have this issue in my desktop computer in the development version of the
site. Just checked the same. So it rules out any issue with import of the
plomino into the ubuntu cloud

On Tue, Mar 24, 2015 at 7:03 PM, Sudhanshu Sekhar Pani <sudhan77@gmail.com>
wrote:

> Yes the form and view both are working.
>
> On 3/24/15, Eric BREHAULT <notifications@github.com> wrote:
> > In your portlet, you are supposed to show a form.
> > Does this form work fine when you open it directly ?
> >
> > ---
> > Reply to this email directly or view it on GitHub:
> > https://github.com/plomino/Plomino/issues/602#issuecomment-85415604
>
>
> --
> Sudhanshu
>



-- 
Sudhanshu

**Comment by sudhan77** [comment]
Dear Eric

I have resolved this issue. You may close the ticket. I am able to see a
form in the portlet. Can a view(created out of a form) be seen in a
portlets.

Regards
Sudhanshu

On Tue, Mar 24, 2015 at 10:42 PM, Sudhanshu Sekhar Pani <sudhan77@gmail.com>
wrote:

> Dear Eric
> I have this issue in my desktop computer in the development version of the
> site. Just checked the same. So it rules out any issue with import of the
> plomino into the ubuntu cloud
>
> On Tue, Mar 24, 2015 at 7:03 PM, Sudhanshu Sekhar Pani <sudhan77@gmail.com
> > wrote:
>
>> Yes the form and view both are working.
>>
>> On 3/24/15, Eric BREHAULT <notifications@github.com> wrote:
>> > In your portlet, you are supposed to show a form.
>> > Does this form work fine when you open it directly ?
>> >
>> > ---
>> > Reply to this email directly or view it on GitHub:
>> > https://github.com/plomino/Plomino/issues/602#issuecomment-85415604
>>
>>
>> --
>> Sudhanshu
>>
>
>
>
> --
> Sudhanshu
>



-- 
Sudhanshu

**Comment by ebrehault** [comment]
ok good, and what was the solution ?

**Comment by sudhan77** [comment]
I had to take to full path of the database for example :
/Plone/plominodb/frmABC and later the element id: frmABC. This resolved one
portlet. However, I still could not resolve another portlet. In the second
portlet I wanted to display the view of a form (example All Form XYZ).
 either I need to find a solution for the same or an alternative.

Thanks

On Thu, Mar 26, 2015 at 2:35 AM, Eric BREHAULT <notifications@github.com>
wrote:

> ok good, and what was the solution ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plomino/Plomino/issues/602#issuecomment-86217575>.
>



-- 
Sudhanshu
