### ISSUE TITLE
Refresh database issue

### ISSUE THREAD

**Issue by sudhan77** [plomino/Plomino#604]
Unable to refresh database. I have deleted some forms and perhaps that is being an issue for the database refresh.
details below, pls help
You are here: Home / MitMit Jobs & Internships
Error
Form configuration does not exist.
Error
Form frmSelectionList_1 does not exist.
Error
Form frmConfig does not exist.
We’re sorry, but there seems to be an error…
Here is the full error message:

Display traceback as text

Traceback (innermost last):

Module ZPublisher.Publish, line 138, in publish
Module ZPublisher.mapply, line 77, in mapply
Module ZPublisher.Publish, line 48, in call_object
Module <string>, line 4, in manage_refreshDB
Module AccessControl.requestmethod, line 70, in _curried
Module Products.CMFPlomino.PlominoDesignManager, line 129, in manage_refreshDB
Module Products.CMFPlomino.PlominoDesignManager, line 234, in refreshDB
Module <string>, line 4, in refreshPortalCatalog
Module AccessControl.requestmethod, line 70, in _curried
Module Products.CMFPlomino.PlominoDesignManager, line 368, in refreshPortalCatalog
Module Products.CMFPlone.CatalogTool, line 353, in catalog_object
Module Products.ZCatalog.ZCatalog, line 476, in catalog_object
Module Products.ZCatalog.Catalog, line 334, in catalogObject
Module Products.ZCatalog.Catalog, line 284, in updateMetadata
Module Products.ZCatalog.Catalog, line 410, in recordify
Module Products.CMFPlomino.PlominoDocument, line 608, in Title
AttributeError: 'NoneType' object has no attribute 'getDynamicDocumentTitle'

**Comment by ebrehault** [comment]
Your document has a `Form` item, indicating the id of the form to use.
If the form is not available in the db, it will break.
So 3 solutions:
- remove the document,
- change the value of its `Fomr` item so it targets an existing form
- create a form having the proper id

**Comment by sudhan77** [comment]
thanks. i am unable to locate the issues. I had deleted the 3 forms earlier

one of the error traces is given below:

Time2015/03/22 12:46:44.188107 GMT-4User Name (User Id)admin (admin)Request
URLhttp://128.199.230.56:8080/kousalam/mitmit_app/manage_refreshDBException
TypeAttributeErrorException Value'NoneType' object has no attribute
'getDynamicDocumentTitle'

Traceback (innermost last):

   - Module ZPublisher.Publish, line 138, in publish
   - Module ZPublisher.mapply, line 77, in mapply
   - Module ZPublisher.Publish, line 48, in call_object
   - Module <string>, line 4, in manage_refreshDB
   - Module AccessControl.requestmethod, line 70, in _curried
   - Module Products.CMFPlomino.PlominoDesignManager, line 129, in
   manage_refreshDB
   - Module Products.CMFPlomino.PlominoDesignManager, line 234, in refreshDB
   - Module <string>, line 4, in refreshPortalCatalog
   - Module AccessControl.requestmethod, line 70, in _curried
   - Module Products.CMFPlomino.PlominoDesignManager, line 368, in
   refreshPortalCatalog
   - Module Products.CMFPlone.CatalogTool, line 353, in catalog_object
   - Module Products.ZCatalog.ZCatalog, line 476, in catalog_object
   - Module Products.ZCatalog.Catalog, line 334, in catalogObject
   - Module Products.ZCatalog.Catalog, line 284, in updateMetadata
   - Module Products.ZCatalog.Catalog, line 410, in recordify
   - Module Products.CMFPlomino.PlominoDocument, line 608, in Title

AttributeError: 'NoneType' object has no attribute 'getDynamicDocumentTitle'

Display traceback as text
<http://128.199.230.56:8080/kousalam/error_log/getLogEntryAsText?id=1427042804.190.339571491215>

REQUESTformsubmit_refresh'Refresh database'cookieslazy itemsSESSION<bound
method SessionDataManager.getSessionData of <SessionDataManager at
/session_data_manager>>otherAUTHENTICATION_PATH''TraversalRequestNameStack[]
LANGUAGEu'en'AUTHENTICATED_USER<PropertiedUser 'admin'>URL'
http://128.199.230.56:8080/kousalam/mitmit_app/manage_refreshDB'SERVER_URL'
http://128.199.230.56:8080'LANGUAGE_TOOL<Products.PloneLanguageTool.LanguageTool.LanguageBinding
instance at 0x7f2d4c6a3ea8>_ec_cache{9568656:
<Products.PageTemplates.Expressions.ZopeContext object at 0x7f2d4d7b9e10>}
PUBLISHED<bound method PlominoDatabase.manage_refreshDB of <PlominoDatabase
at /kousalam/mitmit_app>>method'POST'ACTUAL_URL'
http://128.199.230.56:8080/kousalam/mitmit_app/manage_refreshDB'URL0
http://128.199.230.56:8080/kousalam/mitmit_app/manage_refreshDBURL1
http://128.199.230.56:8080/kousalam/mitmit_appURL2
http://128.199.230.56:8080/kousalamURL3http://128.199.230.56:8080BASE0
http://128.199.230.56:8080BASE1http://128.199.230.56:8080BASE2
http://128.199.230.56:8080/kousalamBASE3
http://128.199.230.56:8080/kousalam/mitmit_appBASE4
http://128.199.230.56:8080/kousalam/mitmit_app/manage_refreshDBenviron
HTTP_REFERER'http://128.199.230.56:8080/kousalam/mitmit_app/DatabaseDesign'
SERVER_SOFTWARE'Zope/(2.13.22, python 2.7.6, linux2) ZServer/1.1'SCRIPT_NAME
''REQUEST_METHOD'POST'PATH_INFO'/kousalam/mitmit_app/manage_refreshDB'
HTTP_ORIGIN'http://128.199.230.56:8080'SERVER_PROTOCOL'HTTP/1.1'QUERY_STRING
''channel.creation_time1427042268CONNECTION_TYPE'keep-alive'HTTP_USER_AGENT'Mozilla/5.0
(Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko)
Chrome/41.0.2272.101 Safari/537.36'SERVER_NAME'kousalam.com'REMOTE_ADDR
'111.91.82.180'PATH_TRANSLATED'/kousalam/mitmit_app/manage_refreshDB'
SERVER_PORT'8080'CONTENT_LENGTH'31'HTTP_HOST'128.199.230.56:8080'
HTTP_CACHE_CONTROL'max-age=0'HTTP_ACCEPT
'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8'
GATEWAY_INTERFACE'CGI/1.1'HTTP_ACCEPT_LANGUAGE'en-US,en;q=0.8'CONTENT_TYPE
'application/x-www-form-urlencoded'HTTP_ACCEPT_ENCODING'gzip, deflate'

On Sun, Mar 22, 2015 at 8:02 PM, Eric BREHAULT <notifications@github.com>
wrote:

> Your document has a Form item, indicating the id of the form to use.
> If the form is not available in the db, it will break.
> So 3 solutions:
>
>    - remove the document,
>    - change the value of its Fomr item so it targets an existing form
>    - create a form having the proper id
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plomino/Plomino/issues/604#issuecomment-84618703>.
>



-- 
Sudhanshu
