### ISSUE TITLE
Dynamic table rendering issue

### ISSUE THREAD

**Issue by mrneverman** [plomino/Plomino#605]
There is document id in first column of dynamic table. and i cannot remove it there. Sample screen shoot is below.
http://i.hizliresim.com/GvA4l6.png

Version Overview
    Plone 4.3.4.1 (4309)
    CMF 2.2.8
    Zope 2.13.22
    Python 2.7.5 (default, Nov 3 2014, 14:26:24) [GCC 4.8.3 20140911 (Red Hat 4.8.3-7)]
    PIL 2.6.1 (Pillow) 
    CMFPlomino 1.19.3

**Comment by ebrehault** [comment]
I cannot see your screenshot, but it sounds as a CSS issue.
Check in your browser debugger.

**Comment by mrneverman** [comment]
there is only below warning in browser :
'webkitIndexedDB' is deprecated. Please use 'indexedDB' instead.

**Comment by ebrehault** [comment]
I menain the network tab, do you see any CSS not loaded ?

**Comment by mrneverman** [comment]
no, it seems everthing is ok. screen shot below again:
http://i62.tinypic.com/30af688.png

**Comment by ebrehault** [comment]
I cannot reproduce the problem.
Can you send me an XML export of your db so I an have a look (put the xml export in gist https://gist.github.com/ )

**Comment by mrneverman** [comment]
https://gist.github.com/mrneverman/f89c748271c970f1a9e3/download#

İts all here. Actually it is just your basic example from your site.

**Comment by ebrehault** [comment]
Ok I got it, it happens with the latest `collective.js.datatables` version (`collective.js.datatables` is a dependency of Plomino).
Just add:
```
collective.js.datatables = 2.0.1
```
in the `[versions]` section of your `buildout.cfg` and re-run buildout.

**Comment by mrneverman** [comment]
Thank you Eric.
problem is gone now.

**Comment by mrneverman** [comment]
We have discovered new situations related this issue.
Regular users (Member Role in plone) having same problem about dynamic table rendering. 
When I give Manager role to the user issue gone away. 

So as a summary:
users who have member role in Plone site cannot see the dynamic table
users who have Manager role in Plone site can see the dynamic table

**Comment by ebrehault** [comment]
- It might be a cache issue (depending on users rights, your Plone site might have different js bundles), so go to zmi / portal_javascript and switch to Dev mode and check if the problem is still there.
- Your users are Plone members but what are their access right in the Plomino db ? (check ACL tab)

**Comment by mrneverman** [comment]
* I switched to Development mode both "portal_css (Registry of CSS files)" and  "JavaScripts Registry portal_javascripts (Registry of JavaScript files) " This does not change anything. 

*Please see below. for ACL tab and roles. 
![plomino1](https://cloud.githubusercontent.com/assets/11598001/7070836/33470f62-deea-11e4-864b-38d113a50954.png)
![plomino2](https://cloud.githubusercontent.com/assets/11598001/7070857/5f552dd2-deea-11e4-9d34-ddd1af6c1df2.jpg)

**Comment by ebrehault** [comment]
And do you get any JS error in your console ?

**Comment by mrneverman** [comment]
There are following errors:

 Consider using 'dppx' units, as in CSS 'dpi' means dots-per-CSS-inch, not dots-per-physical-inch, so does not correspond to the actual 'dpi' of a screen. In media query expression: only screen and (-webkit-min-device-pixel-ratio: 1.5), only screen and (min-resolution: 144dpi)

modernizr.js:6 'webkitIndexedDB' is deprecated. Please use 'indexedDB' instead.

plomino.dynamicview.js:151 Uncaught TypeError: Cannot read property 'oApi' of undefined

viewSubmitOrderenvUserDigikey:443 Uncaught TypeError: undefined is not a function

**Comment by ebrehault** [comment]
Ok, the following error: `plomino.dynamicview.js:151 Uncaught TypeError: Cannot read property 'oApi' of undefined` means that `jQuery.fn.dataTableExt` is not defined, so apprently collective.js.datatables is not installed or loaded properly.
Probably a setup issue, so re-import the collective.js.datatables profile in portal_setup (or just uninstall and reinstall this products with quickinstaller if you prefer)
