### ISSUE TITLE
Error on Save in a Specific Site

### ISSUE THREAD

**Issue by glimmung** [plomino/Plomino#608]
Hi,

I have a Plone 4.3.3 instance with a number of Plone sites, In one particular site, I can define a Plomino db, and manage it through scripting, but if I try to save a record in the UI, I receive the following error message: -

Traceback (innermost last):

Module ZPublisher.Publish, line 138, in publish
Module ZPublisher.mapply, line 77, in mapply
Module ZPublisher.Publish, line 48, in call_object
Module Products.CMFPlomino.PlominoForm, line 426, in createDocument
Module Products.CMFPlomino.PlominoDocument, line 390, in saveDocument
Module Products.CMFPlomino.PlominoDatabase, line 340, in getForm
TypeError: getattr(): attribute name must be string

The error is the same in my production db and in a test db with a form with a single column.

However, if I copy the db to another site on the same server, saving works as expected. It seems that there is some aspect of this site's configuration, or possibly some clashing product, which is causing this behaviour, but I'm unable to identify it thus far.

Is there anything specific I should be looking for? Is there any sort of workaround anyone can suggest?

TIA

Cheers,

PhilK

**Comment by glimmung** [comment]
Just a quick follow up to say that I have now created a test site with exactly the same stack of products, and it behaves as expected - no error message. I don't know where to look further at this point.

**Comment by ebrehault** [comment]
It looks like your current `REQUEST` does not contain a `Form` parameter (or this parameter is not a string).

**Comment by glimmung** [comment]
Hi Eric,

Thanks - I dug a little deeper in reposne to your gentle hint to follow the clues, and the issue seems to be that there is a form from "quickuploader-viewlet" in the action bar, and this form's close tag is closing the Plomino form, such that the form name field is outside the form tags. 

Am on the scent, will confirm when fixed and hopefully close this issue.

--

P

**Comment by glimmung** [comment]
Just to close the loop on this, the issue was Plone Quick Upload, which seems to inject it's form in the middle of Plomino's, prematurely closing the Plomino form prior to the form name field. Removing Plone Quick Upload resolved the issue - it did not uninstall cleanly initially, but once it was gone Plomino burst back into life.

Thanks for prompting me to think a little harder about what the error was telling me - I was over-thinking it! :-)
