### ISSUE TITLE
"About this database" in db home page

### ISSUE THREAD

**Issue by glimmung** [plomino/Plomino#612]
Hi,

This is one that bit me years ago and I think you may have helped me out back on SF, but I cannot for the life of me find the original issue.

I have a db where if I access at /db-name/checkBeforeOpenDatabase I see the expected home page, but if I access it at /db-name, I see the properties info - so "Using this database/ Index file attachments/ 
Local full-text index" etc.

From memory, I had to clear a property that had some been set in the ZMI to clear this, but I can't for the life of me find it now - am I right, and if so can you point me in the right direction, please? 

TIA

--

PhilK

**Comment by ebrehault** [comment]
Yes, you have played with the Display menu, so now the view is wrong.
Go to: `http://server/db/manage_propertiesForm` and delete the `layout` property.

**Comment by glimmung** [comment]
Thank you - again! :-)
