### ISSUE TITLE
advise needed: python programming in plomino

### ISSUE THREAD

**Issue by sudhan77** [plomino/Plomino#614]
This is a dumb query, given my limited understanding of Plomino. I need to use the python formula 'sorted' or similar. Is there a way to use it in plomino. Do I need to create a function and  place it in the resource center and call it in the formula for the variable. please share any example.

**Comment by ebrehault** [comment]
```python
some_docs = [doc1, doc2, doc3]
sorted_by_field1 = sorted(some_docs, lambda x,y: x.getItem('field1') < y.getItem('field1'))
```

See https://docs.python.org/2/library/functions.html#sorted

**Comment by sudhan77** [comment]
I am trying to sort some results inside a plomino document and i get
following errors. Request your help.

line 17, in field_-_InterestProfiler-Web_-_occuCode_-_formula
NameError: global name 'sorted' is not defined
Context is <PlominoDocument>
/mitmit_app/plomino_documents/d034a654ddb04a058fdaa393ab93a402 6:
db=plominoDocument.getParentDatabase()
7: r=['R', plominoDocument.getItem('score')]
8: i=['I', plominoDocument.getItem('scoreInv')]
9: a=['A', plominoDocument.getItem('scoreArt')]
10: s=['S', plominoDocument.getItem('scoreSoc')]
11: e=['E', plominoDocument.getItem('scoreEnt')]
12: c=['C', plominoDocument.getItem('scoreCon')]
13:
14: int=[r,i,a,s,e,c]
15: def Myfn(x):
16:     return x[1]
17: sorted(int, key=Myfn)
18:
19: m1=int[0]
20: m2=int[1]
21: m3=int[2]
22: first=m1[0]
23: second=m2[0]
24: third=m3[0]
25: return first+second+third
26:

On 4/24/15, Eric BREHAULT <notifications@github.com> wrote:
> ```python
> some_docs = [doc1, doc2, doc3]
> sorted_by_field1 = sorted(some_docs, lambda x,y: x.getItem('field1') <
> y.getItem('field1'))
> ```
>
> See https://docs.python.org/2/library/functions.html#sorted
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/plomino/Plomino/issues/614#issuecomment-95884001


-- 
Sudhanshu

**Comment by ebrehault** [comment]
Ok, `sorted` might not be available in your Python version.
Try this:
`int.sort(key=Myfn)`
