### ISSUE TITLE
opening view depending on current user by creating a search form

### ISSUE THREAD

**Issue by sudhan77** [plomino/Plomino#615]
I am trying to open view depending on the current user by creating a search form as given in your 'How To'. In the initial form, I earlier had a text field where the name was being input. However when I am trying to change the field into a name field or add a new name field i get the following errors. Pls help if you can make sense from the error log given below:

We’re sorry, but there seems to be an error…
Here is the full error message:

Display traceback as text

Traceback (innermost last):

Module ZPublisher.Publish, line 138, in publish
Module ZPublisher.mapply, line 77, in mapply
Module ZPublisher.Publish, line 48, in call_object
Module Shared.DC.Scripts.Bindings, line 322, in __call__
Module Shared.DC.Scripts.Bindings, line 359, in _bindAndExec
Module Products.CMFCore.FSPageTemplate, line 237, in _exec
Module Products.CMFCore.FSPageTemplate, line 177, in pt_render
Module Products.PageTemplates.PageTemplate, line 79, in pt_render
Module zope.pagetemplate.pagetemplate, line 132, in pt_render
Module zope.pagetemplate.pagetemplate, line 240, in __call__
Module zope.tal.talinterpreter, line 271, in __call__
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 888, in do_useMacro
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 954, in do_defineSlot
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 858, in do_defineMacro
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 954, in do_defineSlot
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 946, in do_defineSlot
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 858, in do_defineMacro
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 852, in do_condition
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 852, in do_condition
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 533, in do_optTag_tal
Module zope.tal.talinterpreter, line 518, in do_optTag
Module zope.tal.talinterpreter, line 513, in no_tag
Module zope.tal.talinterpreter, line 343, in interpret
Module zope.tal.talinterpreter, line 742, in do_insertStructure_tal
Module Products.PageTemplates.Expressions, line 218, in evaluateStructure
Module zope.tales.tales, line 696, in evaluate
URL: file:/usr/local/Plone/buildout-cache/eggs/Products.CMFPlomino-1.19.3-py2.7.egg/Products/CMFPlomino/skins/cmfplomino_templates/OpenForm.pt
Line 161, Column 24
Expression: <PythonExpr here.openBlankForm(request)>
Names:
{'container': <PloneSite at /kousalam>,
 'context': <PlominoForm at /kousalam/mitmit_app/CareerRoadmap>,
 'default': <object object at 0x7ff71a0304f0>,
 'here': <PlominoForm at /kousalam/mitmit_app/CareerRoadmap>,
 'loop': {},
 'nothing': None,
 'options': {'args': ()},
 'repeat': <Products.PageTemplates.Expressions.SafeMapping object at 0x7ff6fa79e260>,
 'request': <HTTPRequest, URL=http://128.199.230.56:8080/kousalam/mitmit_app/CareerRoadmap/OpenForm>,
 'root': <Application at >,
 'template': <FSPageTemplate at /kousalam/OpenForm used for /kousalam/mitmit_app/CareerRoadmap>,
 'traverse_subpath': [],
 'user': <PropertiedUser 'admin'>}
Module Products.PageTemplates.ZRPythonExpr, line 48, in __call__
__traceback_info__: here.openBlankForm(request)
Module PythonExpr, line 1, in <expression>
Module Products.CMFPlomino.PlominoForm, line 1053, in openBlankForm
Module Products.CMFPlomino, line 167, in newf
Module Products.CMFPlomino.PlominoForm, line 708, in displayDocument
Module Products.CMFPlomino, line 167, in newf
Module Products.CMFPlomino.PlominoField, line 282, in getFieldRender
Module Products.CMFPlomino.fields.name, line 99, in getSelectionList
TypeError: 'NoneType' object is not iterable

**Comment by ebrehault** [comment]
I have just fixed the bug, you can update your sources (or you can just unselect "Do not list portal users" in the db settings).
