### ISSUE TITLE
internal links from plone to plomino

### ISSUE THREAD

**Issue by sudhan77** [plomino/Plomino#616]
I have a plomino database running an app inside a plone site.  plomino 19.2 and plone 4.3.3. However
when i want to create links neither the database nor its contents come
in search for internal links. What should i do. I had imported the
plomino into the production site independently after development.

**Comment by ebrehault** [comment]
- go to Plone site settings / Search, and select PlominoDocument and PlominoDatabase
- go to db settings and check Index documents in Plone portal
- refresh the db
- go to Site setup / TinyMCE Settings / Resource Types, and add PlominoDocument and PlominoDatabase in the "Linkable objects" field.
