### ISSUE TITLE
How do I construct a dbsearch query that returns an And result set? 

### ISSUE THREAD

**Issue by allnode** [plomino/Plomino#617]
I have an application based on the sample code:  http://www.plomino.net/samples/jquery-example 
 
The results field that does the search has code looks like the following. It returns an "Or" selection, how do I code the search argument so that it returns an And selection. 

db = context.getParentDatabase()
query = {'Form': 'beamproject'}

any_criteria = False

job_location = context.REQUEST.get("job_location")
if job_location:
   any_criteria = True
   query['job_location']=job_location

if any_criteria:
  search_results = db.getIndex().dbsearch(query, sortindex = 'programname')
else:
  return """Please select at least one search criterion to see what projects have been registered to the navigator ..."""
search_results_cnt = len(search_results)

Thanks.

**Comment by ebrehault** [comment]
I assume the AND operator must be applied to the job_location criteria (and I assume it is multivalued).
It can be done that way:
```python
query['job_location']={'query': job_location, 'operator': 'AND'}
```

Note: the corresponding field must be indexed as a KeywordIndex.

**Comment by allnode** [comment]
Eric, thanks for you quick reply:  
 
I have the following error   

  line 24, in field_-_copy_of_filteredResults_-_results_-_formula
RuntimeError: operator not valid: AND
Context is <PlominoForm> /Members/kalun/demo-1/copy_of_filteredResults

when I run this search: 
http://www.plomino.com/Members/kalun/demo-1/copy_of_dynamicSearch (I have given you Designer Access to my app): 

My code is for the results field is: 

db = context.getParentDatabase()

query = {'Form': 'frmJob'}

# read submitted criteria
any_criteria = False
job_location = context.REQUEST.get("job_location")
if job_location:
  any_criteria = True
  query['job_location']= {'query' : job_location, 'operator' : 'AND'}

job_skills = context.REQUEST.get("job_skills")
if job_skills:
  any_criteria = True
  query['job_skills']=job_skills

# perform the search
if any_criteria:
  search_results = db.getIndex().dbsearch(query)
else:
  return """Please select at least one criteria..."""
search_results_cnt = len(search_results)

# format the output
html = u''
html += """ %(found)d result(s) found...<br />""" % { 'found': search_results_cnt}
html += "<ul>"
for result in search_results:
  doc = result.getObject()
  html += """<li><a href="%(link)s">%(title)s</a> (%(location)s)
<p><span class="discreet">%(description)s</span></p>
<p>Skills: %(skills)s</p></li>
""" % {'link': doc.absolute_url_path(),
'title': doc.getItem('job_title'),
'description': doc.getItem('job_description'),
'location': doc.getRenderedItem('job_location'),
'skills': doc.getRenderedItem('job_skills'),
}

**Comment by ebrehault** [comment]
My bad, that's not `AND` but `and`.
I have fixed it in your db.

**Comment by allnode** [comment]
Thank you.  I have successfully implemented the "and" function in my non-profit application http://tracker.dmcbeam.org/chna/olmsted-county-community-health/chna_dynamicSearch
