### ISSUE TITLE
hidewhens don't work as expected on a Page Form

### ISSUE THREAD

**Issue by djay** [plomino/Plomino#625]
Get's an error plominoDocument has no method .getItem.

**Comment by jean** [comment]
`.getItem` in dynamic hide-when's work, because a temporary document is constructed for evaluation of the hide-when's.
If you submit to a page form, formulas are executed in the context of a form, so there's no `.getItem`. If you want the formula to check items on a document, you have to create or retrieve that document first.

**Comment by ebrehault** [comment]
As explain by @jean, `getItem` is a Document method, not a Form method, so we cannot use it in Page context. This is probably not documented properly, but we are supposed to use `plominoContext.REQUEST.get()` in a such a case.

**Comment by djay** [comment]
But for a validation formula you use plominoDocument which is a TemporaryDocument created from teh request right? it's not yet saved. So what is the difference with a Page Form? Can't we use TemporaryDocument to achieve a consistent api? Otherwise I have to decode everything from the request manually too.

**Comment by jean** [comment]
> Can't we use TemporaryDocument to achieve a consistent api?

This could make sense, seeing that it already works that way for Dynamic
hidewhens. But things that actually require a Document will never work on a
Form, so we have to be careful up to what point we pretend they work the
same, to avoid creating a rabbit hole.

So far I'm +1

J

**Comment by ebrehault** [comment]
+1 too

**Comment by instification** [comment]
I've created a pull request which should fix this issue. It creates a temporary document to use when running scripts rather than self.

**Comment by ebrehault** [comment]
Thank you.
I have just made a comment regarding your implementation, I will merge the PR once corrected.

**Comment by ebrehault** [comment]
I have reverted the PR

**Comment by ebrehault** [comment]
Fixed by #630
