### ISSUE TITLE
plomino doesn't batch search form results

### ISSUE THREAD

**Issue by djay** [plomino/Plomino#634]
# User problem

Its easy to create a search form with lots of results. Displaying all can kill performance and annoy the user by taking a long time to return. Search forms should batch results by default.

# Options
- make it possible to turn off?
- for backwards compatibility have it turned off for old forms
- should it be using the batching settings for a PlominoView?

**Comment by djay** [comment]
@ebrehault in order to add batching we need a place to store the batch size. I'm guessing the design is such that all such decisions about how the results are displayed is determined by the view right?
Should we add a batch_size/limit field to PlominoView?

**Comment by ebrehault** [comment]
At the moment, the views uses 100 as a default batch size unless we pass a `limit` param in the request to override it (see https://github.com/plomino/Plomino/blob/github-main/Products/CMFPlomino/skins/cmfplomino_templates/OpenView.pt#L138 ).

I guess we can apply for now the same principle to search results for now, considering it is quite easy to pass this `limit` param in that case (we just add a hidden text field named `limit` containing the value we want).

**Comment by djay** [comment]
yep. expect a PR monday right @ivanteoh ?

**Comment by ebrehault** [comment]
Fixed by #638
