### ISSUE TITLE
easy way to ask same questions repeatedly

### ISSUE THREAD

**Issue by djay** [plomino/Plomino#637]
# User problem

Some long forms will ask a same set of questions about different things. Such as workhours first for you, and then for each of your partner and then for each of your children.

# Options

## Manually
current way would be to copy the fields and rename them, then copy the layout or use a subform. Perhaps using hidewhens asking "do you want to add another X?".

## Repeating forms in datagrids

enhance datagrids to allow a repeated questions similar to option1 on https://designpatterns.hackpad.com/Add-edit-delete-loop-WF8hhDeN6yZ (ie no grid)

User
- adds a field of type datagrid (this will have to change. Maybe to "Repeat" or "Repeating Form")
- select "Associated form" (is something like "Add new Form" less confusing? or fields to repeat)
- "Associate form rendering" = "Repeating" instead of "Modal" or "Inline grid". Change question to "Layout"
- "Field rendering", can be "Repeating" to have it like edit mode, or you can choose "Dynamic grid" or "Static grid" to display as a grid
- new property "Max repetitions". Applies in both JS and non JS mode
- click save.
- edit UI has
  - title/legend for each repeat. e.g. Address 1. Using title of subform. Maybe use a fieldset.
  - "delete"below each set of fieds
  - "Add another X" yes/no below all repeating, where X is the title of the subform. In non-JS mode just repeat all to the maximum. 
  - no edit button. Can edit any at any time.

Risks
 - validation could be tricky.

## Prefixes (option 3)
Could have a special "prefix" block which will automatically prefix all fieldids within the block with the prefix. Could wrap it around a subform or a copied layout section in the same form.

**Comment by ebrehault** [comment]
I do not think we should implement something like your option 3. The Plomino answer to this use case is clearly Datagrid.
But of course, Datagrid is not always a good fit in term of rendering or ergonomy.
Maybe we should add a new rendering mode that would actually render the dg fomr entirely for each datagrid entry, instead of boring table rows.

**Comment by djay** [comment]
@ebrehault going to implement repeating forms mode in datagrids

**Comment by djay** [comment]
@ebrehault @jean need some feedback. Here is the settings form I have so far. I've changed the words a lot to try and make it clearer. 
Also I'm a bit confused by Columns/fields mapping. Looking at the code it seems this is compulsory. Shouldn't this be automatic? Perhaps you can explain the idea a bit more @ebrehault ?


<img width="499" alt="screen shot 2016-05-21 at 10 23 21 am" src="https://cloud.githubusercontent.com/assets/41700/15446107/7a2bc0ea-1f3e-11e6-9ca3-5c18c7cdbdd1.png">
<img width="353" alt="screen shot 2016-05-21 at 10 23 43 am" src="https://cloud.githubusercontent.com/assets/41700/15446112/7bca6dca-1f3e-11e6-9a54-eb2a0efe053a.png">
<img width="450" alt="screen shot 2016-05-21 at 10 23 51 am" src="https://cloud.githubusercontent.com/assets/41700/15446113/7dfc9e10-1f3e-11e6-983a-8d39f2c62081.png">

**Comment by jean** [comment]
I think enumerating fields is necessary to allow the subform to have fields that aren't used for columns. 
E.g. a column that is derived from two other fields on the subform.

**Comment by djay** [comment]
@jean not sure I understand

**Comment by ebrehault** [comment]
We need Columns/fields mapping for 2 reasons:

- as @jean said, we might have some fields in the dg form that we do not want to display in grid,
- we need to define the column orders somehow.

**Comment by djay** [comment]
@ebrehault in that case I think it needs to be a required field right? And it should default to being all the fields in the subform? Currently you have to remember all the fieldids. Perhaps it should be a multiselect reorderable widget?

**Comment by jean** [comment]
A reasonable default is to use all the fields in the subform, in the folder order. 
If we accept that as default, then the mapping can be blank. 
I.e. it allows us to override the order and fields used per datagrid.

**Comment by ebrehault** [comment]
I like the @jean proposal.

**Comment by djay** [comment]
Here is it working by the way
![repeatloop](https://cloud.githubusercontent.com/assets/41700/15564654/b461c8e6-233e-11e6-8503-13a723055a43.gif)

**Comment by ebrehault** [comment]
@djay I like it a lot.
Just a question: don't you think the "Include another xxxx Yes/No" is a little misleading? because once a new block has been added, if you select "No", it removes the current block (which is useful, we want to be able to remove blocks of course, but answering "No" to "Include another" in order to remove an existing one sounds strange).

**Comment by djay** [comment]
@ebrehault its even more weird than that. If you click "no" it will remove all the sections below it. The reason I did that is because otherwise it will hide the "include another" from the next section and you won't be able to the hide the one below that.

I need to adjust it. The main reason its as it is is so it works without JS. But perhaps it would be better to change this radio dynamically into a remove button, and an add another button?

**Comment by ebrehault** [comment]
Yes that would be definitely better.

**Comment by djay** [comment]
This has the same issue that if I delete one from the middle then the
numbering is mucked up.
I'd either have to make the number change using js, or just don't have the
numbering in the legend.
