### ISSUE TITLE
How do I obtain a reference to an arbitray plominoDataBase object? 

### ISSUE THREAD

**Issue by allnode** [plomino/Plomino#648]
I know if I wanted to get a reference to the database object that contains the current document, I can use plominoDocument.getParentdatabase() 

I am struggling to find information on how to get the database reference to some other database objects within my plone site.  

I recall seeing info somewhere, I just can't locate that any more.  Thanks for your help.

**Comment by ebrehault** [comment]
If your site is like:
```
/Plone
    /db1
    /db2
```
Frm db1 you can get db2 like this:
```python
current_db = context.getParentDatabase()
db2 = current_db.getParentNode().db2
```

And if your 2 dbs are not that close, it will be probably easier to use `unrestrictedTraverse`:
```python
current_db = context.getParentDatabase()
db2 = current_db.unrestrictedTraverse('/the/path/to/db2')
```

**Comment by allnode** [comment]
When I tried second method, I got  Unauthorized: 

You are not allowed to access 'unrestrictedTraverse' in this context
Context is <PlominoForm> /Members/kalun/samples/DmcAnchorProjectsPortlet

My sample code is ==>  http://www.plomino.com/Members/kalun/samples/DmcAnchorProjectsPortlet/view

**Comment by ebrehault** [comment]
That's an access right issue then.
Is your target db published ?

**Comment by allnode** [comment]
Eric,  I first ran into the problem in my own application and I recreated it in plomino.com . I have given you designer ACL,  if you would take a look. 

My target db (db2) is http://www.plomino.com/Members/kalun/remn-client-relationship-management . It is published. 
My current_db is http://www.plomino.com/Members/kalun/samples/checkBeforeOpenDatabase . It is also published. 

Thanks.

**Comment by ebrehault** [comment]
where is the formula  and how do I reproduce the problem ?

**Comment by allnode** [comment]
My form is located: 
I have re-produced the app as follows: 

My page is located:  
http://www.plomino.com/Members/kalun/samples/artsCultureDiversityPortlet/OpenForm 

My computed for the two computed for display fields are located as follows: 
http://www.plomino.com/Members/kalun/samples/artsCultureDiversityPortlet/display
http://www.plomino.com/Members/kalun/samples/artsCultureDiversityPortlet/displayProjects

You should have manager rights to take a look.

**Comment by ebrehault** [comment]
ok, well yes `unrestrictedTraverse` is forbidden, but you can use `restrictedTraverse`, example:
```db = current_db.restrictedTraverse('../samples')```

**Comment by allnode** [comment]
Thanks!
