### ISSUE TITLE
Access to Replication Tab

### ISSUE THREAD

**Issue by glimmung** [plomino/Plomino#650]
Hi,

Logged into a site with an account with PlominoAuthor rights, the Replication tab is accessible if the URL is known to the user, and shows as a tab on the "About" page (/AboutDatabase). 

What is the most appropriate way to secure this page?

--

Cheers,

PhilK

**Comment by ebrehault** [comment]
To hide the tab: go to ZMI / portal_types / PlominoDatabase / actions (http://your_server/portal_types/PlominoDatabase/manage_editActionsForm) and change the permission for the replication action.

It won't avoid to access the URL if it is known, but there is no consequence regarding security, as the replication will always apply the current user security access rights (so for instance it would not change a document the user is not allowed to edit).
