### ISSUE TITLE
how to upgrade

### ISSUE THREAD

**Issue by sudhan77** [plomino/Plomino#659]
my plomino design tab shows plomino version 19.2. while i run my buildout it shows that it is installing some requirements for version 19.3. how do i upgrade my plomino. my plone instance is 4.3.6 currently

**Comment by ebrehault** [comment]
The design tab shows the db structure version.
As the db structure does not necessarily change at every Plomino version, the db version and the Plomino version might be different.
19.2 corresponds to the last db structure change so it is correct, and it can work with Plomino 1.19.3 (or higher).
