### ISSUE TITLE
Logged warning on views for empty columns

### ISSUE THREAD

**Issue by glimmung** [plomino/Plomino#662]
Hi,

I'm looking at some views which are rather slow, and I see that there is some very verbose logging going on, like: -

2015-09-07T10:20:47 WARNING Plomino PlominoColumn.getColumnRender> viewname/fieldname is Missing.Value

...which is correct (these record have been imported from CSV, so empty fields have a type but no value), but which I'm not sure should trigger a warning. If I use a formula: -

plominoDocument.getItem('fieldname') 

...no warning is logged, but of course this does not apply to auto-generated queries.

This looks like at least part of my performance issue - Should I strip fields/attributes which have no value after import?

--

PhilK

**Comment by ebrehault** [comment]
Yes, I think this big warning amount can slow down the server.
Either you use a formula (as yo usaid) for those columns, either you change the default log level for your server (use ERROR level, which is recommanded for production server, os warnings are not displayed).
