### ISSUE TITLE
Display message when no document found

### ISSUE THREAD

**Issue by shamille** [plomino/Plomino#690]
Feel like I'm missing something obvious, but I'm unable to display a message to users when a database search returns no documents. I can display messages based on search criteria by adding, e.g., the following to a search form Search formula:
```python
 if plominoDocument.getItem('lastname') == 'Jones':
     plominoDocument.writeMessageOnPage('You are Jones, yes?', plominoDocument.REQUEST)
 else:
     plominoDocument.writeMessageOnPage('Sorry, no Jones found', plominoDocument.REQUEST)
```
But if a user searches for an individual who isn't in the database -- and, thus, isn't Jones -- no message is displayed. I take it this is because the Search formula must have some document or other to operate upon. 

I've inherited this database at work, and don't really have any facility with python, but I've read through https://plomino.readthedocs.org/en/latest/classes and https://plomino.readthedocs.org/en/latest/features/, and tried lots of different things, and I'm stumped. Any help is greatly appreciated. Thanks!

**Comment by ebrehault** [comment]
Apparently you are using a regular Search form, and that's true, it does not display anything when no results.
The best solution is probably to create a Page form instead, where you will display your search results in a computed for display richtext field, and in this field formula, you will be able to test the amount of results and display a messgae if no result.

**Comment by shamille** [comment]
I understand how to use computed for display richtext fields, but I'm not clear on how to get my search results into a page form that contains such a field. Search forms, as far as I can tell, require views, which determine how results display. Is the idea to somehow use a page form instead of a view to display results?

**Comment by shamille** [comment]
I'm able to get the behavior I want by modifying the searchDocuments function in PlominoForm.py. I just return a message to the user when the filteredResults list is empty:
```python
if not filteredResults:
    return("Nothing to see here.")
```

**Comment by ebrehault** [comment]
TRue, that's a very good approach.
