### ISSUE TITLE
plomino 2.0a3 - error in changing document title

### ISSUE THREAD

**Issue by sudhan77** [plomino/Plomino#695]
I am trying to change document title.
return " Current State "

I get following errors:

Error Title formula failed - Plomino traceback line 7, in form_-_currentstatefrm_-_title <br/>AttributeError: getCurrentUser <br/>Context is &lt;PlominoDocument&gt; /CareerPlanning/mitmit/plomino_documents/8b20fef6-0711-4915-a50d-43b0bde4d16e

**Comment by ebrehault** [comment]
It seems not related.
Are you sure your formula has been recompiled ?
(goes to /scripts folde in ZMI and have a look)

**Comment by sudhan77** [comment]
Dear Eric

I went to scripts folder in ZMI. the formula has not been changed. I
changed the formula and problem solved.
But i am not able to make changes to the document title formula TTW. Am I
missing something?

Thanks

On Fri, Oct 30, 2015 at 2:35 PM, Eric BREHAULT <notifications@github.com>
wrote:

> It seems not related.
> Are you sure your formula has been recompiled ?
> (goes to /scripts folde in ZMI and have a look)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plomino/Plomino/issues/695#issuecomment-152465363>.
>



-- 
Sudhanshu

**Comment by ebrehault** [comment]
Indeed that was a bug.
Fixed with https://github.com/plomino/Plomino/commit/024c503d2eab65b5cb25b6b0f80bf587aee5b511
