### ISSUE TITLE
Field order in Dates

### ISSUE THREAD

**Issue by glimmung** [plomino/Plomino#699]
I have a db which uses UK (dd/mm/yyyy) date format, but the order of the selects in data entry is yyyyy/mm/dd, and looking at the code in DATETIMETool.pt this seems to be hard coded.

Am I missing something here, or is the appropriate way to get UK ordering to customise DATETIMETool.pt and DATETIMEFieldEdit.pt?

**Comment by glimmung** [comment]
I should mention that in a perfect world I would use the JQuery UI datetime widget, but this is for a date of birth, and I cannot for the life of me work out how to tweak the JS to get the year as a dropdown.

**Comment by ebrehault** [comment]
The date input widget cannot be customized and it uses YYYY-mm-dd.
The formatting only applies to read mode.

**Comment by djay** [comment]
shouldn't it use plones localisation settings?

**Comment by ebrehault** [comment]
It should, but it does not (as far as I know).
By the way, I am not even sure the official HTML5 date widget does use the system locale settings.

**Comment by djay** [comment]
No I wouldn’t want it to be localised to the browser environment. I would expect it to use plone set locale, ie where the plone site has been set to server to. So the date looks like all other plone dates.
