### ISSUE TITLE
Setting "From" in plominoDocument.send()

### ISSUE THREAD

**Issue by glimmung** [plomino/Plomino#700]
Hi,

I have a form which is intended to send an email using plominoDocument.send() - however, the form is submitted by an anonymous user, so the mail send fails for lack of a from address.

Is there a way to set the sender in this function, or a workaround of some sort?

--

PhilK

**Comment by ebrehault** [comment]
The `send()` method does allow to set the sender.
You must use the `sendMail()` from PlominoUtils which accepts a `sender` param.
And to get a mail content similar to the one sent by `send()`, just use `form.displayDocument(doc)`.
