### ISSUE TITLE
Got an error trying to get into Plomino Designer 

### ISSUE THREAD

**Issue by allnode** [plomino/Plomino#707]
All of a sudden I got this error when I attempt to get into my database designer.  

Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module Shared.DC.Scripts.Bindings, line 322, in __call__
  Module Shared.DC.Scripts.Bindings, line 359, in _bindAndExec
  Module Products.CMFCore.FSPageTemplate, line 237, in _exec
  Module Products.CMFCore.FSPageTemplate, line 177, in pt_render
  Module Products.PageTemplates.PageTemplate, line 79, in pt_render
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module zope.pagetemplate.pagetemplate, line 240, in __call__
  Module zope.tal.talinterpreter, line 271, in __call__
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 888, in do_useMacro
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 954, in do_defineSlot
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 858, in do_defineMacro
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 954, in do_defineSlot
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 946, in do_defineSlot
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 858, in do_defineMacro
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 821, in do_loop_tal
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 821, in do_loop_tal
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 533, in do_optTag_tal
  Module zope.tal.talinterpreter, line 518, in do_optTag
  Module zope.tal.talinterpreter, line 513, in no_tag
  Module zope.tal.talinterpreter, line 343, in interpret
  Module zope.tal.talinterpreter, line 620, in do_insertText_tal
  Module Products.PageTemplates.Expressions, line 225, in evaluateText
  Module zope.tales.tales, line 696, in evaluate
   - URL: file:/app/plone433/buildout-cache/eggs/Products.CMFPlomino-1.18.6-py2.7.egg/Products/CMFPlomino/skins/cmfplomino_templates/DatabaseDesign.pt
   - Line 116, Column 36
   - Expression: <PythonExpr column.getColumnName()>
   - Names:
      {'container': <PlominoDatabase at /chna/olmsted-county-community-health>,
       'context': <PlominoDatabase at /chna/olmsted-county-community-health>,
       'default': <object object at 0x7f6a13b5bb60>,
       'here': <PlominoDatabase at /chna/olmsted-county-community-health>,
       'loop': {u'column': <Products.PageTemplates.Expressions.PathIterator object at 0x7f69f15c8390>,
                u'view': <Products.PageTemplates.Expressions.PathIterator object at 0x7f69da2d6310>},
       'nothing': None,
       'options': {'args': ()},
       'repeat': <Products.PageTemplates.Expressions.SafeMapping object at 0x7f69fc26b470>,
       'request': <HTTPRequest, URL=http://dmc.middlewaygroup.org/olmsted-county-community-health/DatabaseDesign>,
       'root': <Application at >,
       'template': <FSPageTemplate at /chna/olmsted-county-community-health/DatabaseDesign>,
       'traverse_subpath': [],
       'user': <MembraneUser 'support'>}
  Module Products.PageTemplates.ZRPythonExpr, line 48, in __call__
   - __traceback_info__: column.getColumnName()
  Module PythonExpr, line 1, in <expression>
AttributeError: getColumnName

**Comment by ebrehault** [comment]
It looks like a problem with a column, no idea how it happened.
To identify the corrupted column:
- copy your db,
- in the copy, delete the views one by one until the problem disappear,
- once you know which view is guilty, make a new db copy, and delete the columns one by one

**Comment by allnode** [comment]
Thanks for your suggestion. I will need to take a bit of time to do that. In the meantime, is there work around? For example, is there a "backdoor" way to re-index the database without going through the Designer?

**Comment by ebrehault** [comment]
You can go to the ZMI, go in your db then  in the plomino_index, and in Advanced tab you can update the index.

**Comment by allnode** [comment]
I have isolated to the error to be in 

    Module Products.CMFPlomino.PlominoDesignManager, line 129, in manage_refreshDB
    Module Products.CMFPlomino.PlominoDesignManager, line 209, in refreshDB

AttributeError: getColumnName 


 #declare all the view formulas and columns index entries
        for v_obj in self.getViews():
            index.createSelectionIndex(
                    'PlominoViewFormula_' + v_obj.getViewName())
            for c in v_obj.getColumns():
                v_obj.declareColumn(c.getColumnName(), c, index=index)

What is the python code I patch into Plomino code to list view name(s) when I run in foreground mode to the terminal? So I can tell which View causes the problem.

**Comment by ebrehault** [comment]
You can log messages like this:
```logger.info("Current view:" +  v_obj.getViewName())```

**Comment by allnode** [comment]
Thanks. With the patch, I was able to find three views that have been corrupted for "unknown" reasons. After deleting the views, things are back to normal.
