### ISSUE TITLE
CMFPlomino product appears to break styles in Plone 4.3.3

### ISSUE THREAD

**Issue by AshRaghav** [plomino/Plomino#723]
Hi all,

I am facing a very weird problem when I try to add CMFPlomino add-on to a vanilla plone install (v4.3.3 - Sunburst theme), the product breaks styles in overlapping divs like "Add new user" (in Users and groups), "New Theme" and "Upload zip file" (in Theming doesn't open the div at all) and other places where there is popup div or dropdown menu used. Even the dropdown which opens up to User Actions such as "Preferences", "Site setup", "Logout",etc at the top-right corner opens in a separate page instead of a popup. I have attached files from both behaviours (with and without CMFPlomino product)

The installation I use is Plone 4.3.3, CMF 2.2.7, Zope 2.13.22, Python 2.7.6, CMFPlomino Product 1.19.6 and Ubutu 14.04 LTS. I tried replace CMFPlomino 1.19.6 with 1.19 (which is running okay in another application of Plone 4.3.3) but no avail. I have attached the log snippet for this add-on product, if that helps.

I am not very sure what I messed up with the installation but everything appears okay at first look. There is clearly a clash between bootstrap styles and CMFPlomino's styles but I can't figure out what it is conclusively. 

Can someone kindly throw some light on what I might be missing in this case?

Thanks in advance

![menu behaviour without cmfplomino product](https://cloud.githubusercontent.com/assets/18511903/15401256/94143af4-1de6-11e6-84ee-c4fe01556b56.jpg)
![menu behaviour with cmfplomino product](https://cloud.githubusercontent.com/assets/18511903/15401257/9416d85e-1de6-11e6-9380-8f704ac3b99f.jpg)
[CMFPlomino product installation log.txt](https://github.com/plomino/Plomino/files/273016/CMFPlomino.product.installation.log.txt)

**Comment by ebrehault** [comment]
That's definitely a JS conflict.
As mentionned here https://github.com/plomino/Plomino/tree/1.x, you need to pin collective.js.datatables = 2.0.1 in your versions.cfg, re-run buildout and uninstall/reinstall collective.js.datatables.
