### ISSUE TITLE
Plomino 2 : Split plomino.designportlet into database, form and view portlets

### ISSUE THREAD

**Issue by sverbois** [plomino/Plomino#730]
### DataBase portlet
**Title of my DaTabase** (portlet header)
_Database_
- Parameters
- Design
- Access control
- Import/export

_Forms_ +
- my-first-form
- my-second-form

_Views_ +
- my-first-view
- my-second-view

_Agents_ +
- my-first-agent
- my-second-agent

### Form portlet
**Title of my Form** (portlet header)
View | Edit | Content
_Fields_  +
- field_one
- field_two

_Hide when_ +
_Actions_ +
- action_x
- action_y

_Caches_

### View portlet
Same structure.

**Comment by ebrehault** [comment]
Be aware we are working on a new Plomino IDE (see #705, implemention is on going in this branch https://github.com/plomino/Plomino/tree/ide).
So we do not plan to change the Design portlet too much (as the IDE will be a much more powerful tool).

**Comment by sverbois** [comment]
#705 is indeed much more ambitious. I close this issue.
