### ISSUE TITLE
RestrictedPython doesn't work on TempDocs in Plomino 2

### ISSUE THREAD

**Issue by instification** [plomino/Plomino#755]
# User Problem

You want to use a formula to re-use selection lists between forms. You create a `frmConfiguration` form with the selection list field and then another form which calls a utility script.

You would have some resources code such as:

```
db = plominoContext.getParentDatabase()
config = db.getDocument('configuration')
frmConfig = db.getForm('frmConfiguration')

def libConfig_getSelectionList(key):
    selection_list = []
    form_field = frmConfig.getFormField(key)
    if form_field:
        selection_list = form_field.getSettings().getSelectionList(config)
    return selection_list
```

However, calling this function in a selection formula raises an Unauthorized exception:

```
Unauthorized: You are not allowed to access 'getSelectionList' in this context
Context is <TemporaryDocument> /Plone/test/TEMPDOC
```

This functionality was previously working in Plomino v1.

A major difference between versions is the switch to Dexterity. The `getSettings()` method now returns an adapter, whereas previously it was an object with acquisition etc.

I have tried adding `security.declarePublic` declarations to the `getSettings` (in https://github.com/plomino/Plomino/blob/master/src/Products/CMFPlomino/contents/field.py)  and `getSelectionList` (in https://github.com/plomino/Plomino/blob/master/src/Products/CMFPlomino/fields/selection.py) functions in , but still getting the same `Unauthorized` exception.

**Comment by displacedaussie** [comment]
@instification in our multipage-p2 branch I've added a getSelectionList method to the PlominoField class. I wasn't able to wrap appropriate security declarations around the method(s) in the fields themselves. 

You can now do something like:

```
field = form.getFormField('myfield')
options = field.getSelectionList(config)
```
