### ISSUE TITLE
Change PlominoDatabase to App or Application

### ISSUE THREAD

**Issue by djay** [plomino/Plomino#760]
Some apps don't store data. Some Apps are single page forms. We should make it approachable to create a forms inside Plone. We can't call it a Form since it can contain many forms and views. Form Folder is meaningless. App seems like the best choice I can think of. It still keeps the idea that an App might store data.

The experience to create a quick App could be
1. Go to contact-us folder
2. Click "Add new..." > "App"
3. Be presented with an empty form (already set as default view).
4. Drag in fields and start creating custom contact us form
5. Select macro "email on submit" and enter details
6. publish in plone.

**Comment by djay** [comment]
what do you think @ebrehault ?

**Comment by ebrehault** [comment]
It sounds strange to add an extra entry in the Plone "Add new..." menu to create a given type of Plomino db.
It is just like if we add a specific entry "News collection" just to create a collection of news.

The ability to create pre-built Plomino dbs for certain usages is an existing feature of Plomino (database templates which can be imported with GS), and that's the first thing the user sees after creating an empty db. So to me, that's good enough, no?

**Comment by djay** [comment]
Sorry if there is confusion. My suggestion is replace the word
plominodatabase with the word app.

**Comment by ebrehault** [comment]
Oh :), well yes I agree it is much better. But do you think we can get eliminate the word "Plomino"?
"Plomino app" would make clear it is a Plomino app, no?

**Comment by djay** [comment]
@ebrehault I find it makes the UI confusing. PFG doesn't say its a PFG form. You add a "Form" (or rather "Form folder"). You add Video objects with wildcard media. The people who install the plugin might not be the people who use it. The only time this becomes an issue is if you have two plugins that provide the same functionality but that case is rare and there are other ways to solve it. From a user point of view they are creating an App which is one or more Forms.

**Comment by djay** [comment]
I'm hoping now with the visual fields and macros that it should be more intuitive and require less knowledge. Perhaps when they create an app there is a wizard/macro to choose a basic initial structure. Either a single form, or a crud (view + form). Then they drag in fields. Use an submission macro on the form to pick where the data goes. Then it can replace easyform or PFG.

**Comment by djay** [comment]
closing this in favour of https://github.com/plomino/Plomino/issues/774
