### ISSUE TITLE
pickadate Jquery datetime widget doesn't work with a non default date format

### ISSUE THREAD

**Issue by ivanteoh** [plomino/Plomino#765]
# Problem

If you set the datetime widget to have a format such as '%d %B %Y' , the format is not passed to the pickadate js. The consequence is that it misinterprets the date. If you hit save you might change the date to another one.

# Internal

datetime_edit.pt doesn't pass the format info to pickadate. It can support passing the format info but its a different kind of format definition from pyhon http://amsul.ca/pickadate.js/date/#formatting-rules and https://docs.python.org/2/library/datetime.html#strftime-and-strptime-behavior

If you look at mockup/patterns/pickadate/pattern.js and mockup/patterns/querystring/pattern.js, it is possible to accept format variable in `data-pat-pickadate`. for example, `{"time": false, "date": {"format": "dd mmmm yyyy" }}`.

# Options

[ ] disable 'JQuery datetime widget'
[ ] send formatting to pickadate. convert python date format to pickadate format.
[ ] Set a constant format so that JQuery widget will understand the datetime format

**Getting the right value**
<img width="1119" alt="correct" src="https://cloud.githubusercontent.com/assets/900434/19139016/de38452c-8bcc-11e6-83ad-97a66bd56794.png">

**Getting the wrong value**
<img width="1128" alt="wrong" src="https://cloud.githubusercontent.com/assets/900434/19139024/ed548598-8bcc-11e6-9a8c-fb9107c281c9.png">

**Comment by ebrehault** [comment]
I guess option 2 would be the best, but if too complex we might go with option 3.
