### ISSUE TITLE
Selection list formula

### ISSUE THREAD

**Issue by ermancio** [plomino/Plomino#776]
Hi all.
I have 2 forms in a Plomino database, _customers_ and _documents_.
I have a selection list field called client in the form _documents_ and i want to show my customer descripition in it.
How can I show values from another form on my selection list?
Thank you
Luca

**Comment by ebrehault** [comment]
Before answering, just a small note about vocabulary:

- a **form** is a way to display some fields using a given layout,
- when you open a form, fill in the field and save, it produces a **document**
- a document can be display and/or modified using different forms than the one used to create it originally.

So your question is how to list "customers" documents in your "documents" form:

- create a view that will list all the "customers" documents
- replace your selection field with a doclink field, and put your view in the Source view param (and an appropriate column in the Label column param)

**Comment by ermancio** [comment]
Thank you very much Eric.

**Comment by ermancio** [comment]
One more question:
If I use such a view, whenever I save my doc, Plomino shows also the doc in the customer view.
I have for example, 2 customers. I use doclink field and I'm able to see them and select one to save data but Plomino shows the saved document in the source view.
I tried to use another Plomino DB for _Customers_ using restricted traverse; everything is ok but the customer name I select,  was saved in the doc (I see it in the document properties) but it's not showed in the document.
What's happening?

**Comment by ebrehault** [comment]
instead of using a view, you can write your own selection formula

**Comment by ermancio** [comment]
I did it in this way before reading you...ah ah
Thank you
L.
