### ISSUE TITLE
autoincrement number field

### ISSUE THREAD

**Issue by ermancio** [plomino/Plomino#777]
Hello everybody.
I need to implement a number field which must be incremented on every document saving (on save event, I suppose).
So I have a form and everytime I save a document, my Id number Field must be valued with "plus one" starting from the last saved document ID.
Any hint?
Thank you

LM

**Comment by ebrehault** [comment]
Here is an article about this subject: https://github.com/plomino/Plomino/wiki/HOW-TO-implement-an-auto-increment-chrono

**Comment by djay** [comment]
I think this would make a good macro.

**Comment by ermancio** [comment]
I had already read the article but the referred solution increments the ID everytime I open/edit the document.
What I need is to add 1 (respect to the last saved ID) to every new saved document.

**Comment by ebrehault** [comment]
Be careful, you need to use a "Computed on creation" field, that way its is computed only when a doc is created (not every time the doc is saved).

**Comment by ermancio** [comment]
Gonna try again and I'll let you know

**Comment by ermancio** [comment]
Well, when I open my form, ReferenceID increments (starting from **0**) and it is **1** but when I fill all the fields and save, the ReferecenceID field becomes **2**.
If I edit and save the document, ReferenceID remains 2.

**Comment by ermancio** [comment]
This is the code I use in the formula field of the ReferenceID

_db=plominoDocument.getParentDatabase()
searchchrono=db.getIndex().dbsearch({"Form": "frmChrono"})
chronodoc=searchchrono[0].getObject()
currentvalue=chronodoc.chrono
newvalue=currentvalue+1
# store back the new chrono in the chrono doc
chronodoc.setItem("chrono", newvalue)
# return the reference id properly formatted
return "%03d" % newvalue_

**Comment by ermancio** [comment]
..and if I use the code for the ReferenceID as Computed on save field, it works fine on save but the field is incremented on edit+save....
