### ISSUE TITLE
Mailhost not sending mail when submitting a form as an Author

### ISSUE THREAD

**Issue by AshRaghav** [plomino/Plomino#781]
Hi,

I have created a form with 5-6 fields and on submission, I am triggering an email using context.Mailhost.send. 

Apparently, this works when I try with Manager roles but mail sending is not working when I try submitting as an Author. 

I tried tweaking the security permissions in ZMI Mailhost with no avail. 

Is there any other configuration that I am missing which is preventing authors and other roles from sending emails? 

Thanks.

**Comment by AshRaghav** [comment]
Think I managed to resolve it. 

Had to give "Use Mailhost services" permission to Authenticated, Contributor, Editor and Owner. Or probably Authenticated was what it would've been mainly looking for. 

It would've been quite useful if I had a permissions error in the logs but nothing showed up unfortunately :-( 

In all cases, it is resolved now.

**Comment by djay** [comment]
@AshRaghav this can now be solved another way by using the new runAsOwner api. https://github.com/plomino/Plomino/pull/788

**Comment by AshRaghav** [comment]
@djay thanks - that is quite useful to know.
