### ISSUE TITLE
Error on Plone 5

### ISSUE THREAD

**Issue by ermancio** [plomino/Plomino#784]
Hi all.
I installed Plomino 2.0a5 on Plone 5 (on a virtual machine - Virtual box - with ubuntu 15.10).
Now I'm trying to add a new plone site with Plomino as addon but I have the following error:

**Error Type: ValueError
Error Value: Cannot find a field for the record plone.bundles/plomino.merge_with. Add a <field/> element or reference an interface and field name.**

Could anybody help me before trying to reinstall everything?
Luca

**Comment by ermancio** [comment]
I reinstalled evertyhing but now I have a strange error.
When i start Plone, instancepid and instantlock files are generated continously; plone restarts every 30 seconds so that it doesn't work.
The referred 2 files are always deleted and re-created
Could anybody help me, please?

Luca

**Comment by ermancio** [comment]
Ok.
On Plone 5, I need to use Plomino 2...

**Comment by ebrehault** [comment]
So, did you sort it out? (if so, close the issue please)

**Comment by ermancio** [comment]
OK, sorry
