### ISSUE TITLE
How to program an Action to reset several mult-select fields to emplty

### ISSUE THREAD

**Issue by allnode** [plomino/Plomino#785]
I have a search form that have many selectable fields.  I'd like to provide a "Reset Button" to allow the user to empty out the selections. What is the python code to do that. 

Here is link my form http://dmcbeam.org/olmsted-county-community-health/frmWideSearchGeneralFront

**Comment by ebrehault** [comment]
There is no Python code for that, moreover it would not make sense to submit a page in order to get an empty form in return.
It must be done in javascript, like this:
```$('#plomino_form')[0].reset()```

It can be embedded in a button produced with a computed for display rich text field:
```html = """<button onclick="$('#plomino_form')[0].reset(); return false;">Reset</button>"""
return html```

**Comment by allnode** [comment]
Thank you. It works.
