### ISSUE TITLE
Import / export JSON file does not preserve the order in folder content 

### ISSUE THREAD

**Issue by ivanteoh** [plomino/Plomino#791]
# Step to reproduce

1. Re-order the forms in the folder content on the current Plomino database
2. Export the Plomino database to 'db.json'
3. Create a new Plomino database
4. Import 'db.json' to the new Plomino database
5. The order for the forms on new Plomino database is not the same as the current Plomino database

It would be hard to fix since JSON format ignore the order

# Options

- [ ] Change the dict to list
- [ ] add order attribute in the form object

**Comment by djay** [comment]
turns out there is a third options. You can make python json use ordereddicts
