### ISSUE TITLE
Plomino content disappears when upgrading to Plone 5

### ISSUE THREAD

**Issue by cdw9** [plomino/Plomino#801]
It's possible I just need instructions for migrating to Plomino 2.0, I did not find any.

Here are the steps I followed:

* In Plone 4.3.6, reinstall Plomino so it is on 1.19.5
* Update buildout to Plone 5. 
* Before running the upgrade to Plone 5, reinstall Plomino so it is on 2.0b6
* At this point, the Plomino content is still there
* Upgrade to Plone 5
* Plomino content is now gone. It does not show up when I browse the catalog's `portal_type` index. Going to the content url shows `<persistent broken Products.CMFPlomino.PlominoDatabase.PlominoDatabase instance '\x00\x00\x00\x00\x00\x03\x10\x1e'>`
* Plomino is still installed, and I can add new content.

Am I missing steps?

**Comment by ebrehault** [comment]
Hi Chrissy,

I though it was documented but apparently it is not, sorry.
The migration is based on import/export:

- In Plone 4.3.6, reinstall Plomino so it is on 1.19.5
- In your Plomino db design tab, you will get a new export format ("To Json File (Migrate to Plomino 2)"), it will allow you to export your db design in a Plomino2 compliant JSON format
- In your Plomino replication design tab, you will get the same so you can export your db documents in a Plomino2 compliant JSON format
- Now you have to delete your existing db (yeah I know, it sounds scary)
- Update buildout to Plone 5
- Before running the upgrade to Plone 5, reinstall Plomino so it is on 2.0b6
- Upgrade to Plone 5
- Create a blank db to replace your old db
- Go to Design and import the design json file
- Go to Import/export and import your documents json file

I will update the documentation.

**Comment by ebrehault** [comment]
here: https://github.com/plomino/Plomino/wiki/HOW-TO-migrate-from-Plomino-1-to-Plomino-2

**Comment by cdw9** [comment]
Thank you! If you don't mind, I will update that wiki page as I test to fix anything that is wrong. (For example, I see the version in Plone 4 should be 1.19.6)

**Comment by ebrehault** [comment]
Please do, I have invited you to this organization so you can get write access on the wiki.
