### ISSUE TITLE
Exporting Richtext fields to Excel/CSV

### ISSUE THREAD

**Issue by AshRaghav** [plomino/Plomino#803]
Hi,

I am sorry if this appears to be a dumb question but just curious to know the reason behind not showing Richtext data in Views' columns and subsequently disallowing exports to Excel/CSV. 

Is this because of the formatting which might end up breaking the HTML? or some other reason beyond a amateur developer's understanding? 

It would be so useful to be able to see the Richtext data in a column and available for export but unfortunately this is not the case at the moment. Not able to find any references to previous discussions in Git :-(

Any light on this area is much appreciated. 

Thanks

**Comment by ebrehault** [comment]
Richtext fields are supported in views.
In the default view you get when you click "Generate view" from a form, we only pick fields which are supposed to be the most relevant (so we exclude FileAttachments, Datagrids, RichText, etc, which are more about form rendering than basic data about the doc). But still, you are free to add a new column containing a richtext field at anytime.
