### ISSUE TITLE
Date time fields can't be output with timezones

### ISSUE THREAD

**Issue by djay** [plomino/Plomino#809]
Looking at zopes strftime function it actually tries to convert the store time to be the localtime zone and then deliberately passes it to datetime.strftime as timezonenieve. Then "%z" and "%Z" get displayed as empty. 
This could have other implications. For example a time stored without DST could change when displayed during DST. 

I suspect the best solution is to call .todatetime.strftime directly. Not sure if this will have other implications.

**Comment by djay** [comment]
Not sure If you came across this issue before @ebrehault

**Comment by ebrehault** [comment]
Yes I think .todatetime.strftime will work and is a better approach (I have never been playing with multi timezone though).
