### ISSUE TITLE
ordering dynamic table view for date column

### ISSUE THREAD

**Issue by ermancio** [plomino/Plomino#816]
Hi,
I have a view with a column returning a date field (dd/mm/YY).
In the formula I have
plominoDocument.getRenderedItem('MyDate')

In my view (dynamic table) , it's not possible to order by date (clicking on the column header) beacuse It orders by the first number (day).
How can I allow such a ordering?
Thank you

Luca

**Comment by ermancio** [comment]
In other words i need to order for date (dd/mm/YY) in the dynamic view

**Comment by ebrehault** [comment]
In your formula where you compute the datagrid row values, you can add an extra value that will be the date (not rendered), so you can sort the rows according this value, and then return the other values only.

Example:
```
gridvalues = [[date1, a1, b1, c1], [date2, a2, b2, c2], [date3, a3, b3, c3]]
gridvalues.sort(key=lambda x: x[0]) # that's how we sort according the first value of each row
gridvalues = [row[1:] for row in gridvalues] # that's how we remove the first value of each row
```
