### ISSUE TITLE
sting and int from a datagrid

### ISSUE THREAD

**Issue by ermancio** [plomino/Plomino#817]
Hi.
I need to define a plomino field which calculates (on save) a sum of plomino number field from a datagrid.
I'm able to retrieve data from datagrid but I can't sum them (they come in string format from the datagrid).
I try to explain better.
In my main Form (with a datagrid called _MyDataGrid_ related to my _Subform_) I set onsave event for _MyNumberField_ (my computed On save number field) with the following code:

lista=''
for _Subform_ in (plominoDocument.getItem('_MyDataGrid_')):
lista = lista + str(_MySubField_[2])
listaInt = int(lista)
plominoDocument.setItem('_MyNumberField_', listaInt)

For example, I have two values in two different rows in _MyDataGrid_ (MySubField = 2000 and MySubField = 5500); onsave the result is 20005500 in _MyNumberField_.
I would like to sum the two values to obtain 7550.

Any hint?

Luca

**Comment by ebrehault** [comment]
You just need to convert values to int **before** summing (and not after as you do currently):
```
lista=0
for Subform in (plominoDocument.getItem('MyDataGrid')):
    lista = lista + int(MySubField[2])
plominoDocument.setItem('MyNumberField', lista)
```
