### ISSUE TITLE
'Form formula' in view no longer works in 2.x

### ISSUE THREAD

**Issue by ivanteoh** [plomino/Plomino#825]
### In Plomino 1.x

This URL format `<db_url>/<view_id>/<doc_id>` will be display in 'view_id' view and when this URL is opened, the document will display with the form name in 'Form formula'.

When I looked into the code, I notice 'evaluateViewForm' method in 'PlominoView' class, that inherited with 'ATFolder' class, is called in 'getForm' method in 'PlominoDocument' class.

### In Plomino 2.x

'This page does not seem to exist...' is raised when this URL format `<db_url>/<view_id>/<doc_id>` is opened.

When I looked into the code, I notice 'evaluateViewForm' method in 'PlominoView' class, that inherited with 'Container' class, is called in 'publishTraverse' method in 'DocumentView' class.

The implementation is different in both versions. What is your plan for this feature, https://plomino.readthedocs.io/en/latest/features/#form-formula?

**Comment by ivanteoh** [comment]
Because 'base_url' in View is wrong. The correct URL format should be `<db_url>/<view_id>/<document>/<doc_id>`.

**Comment by ebrehault** [comment]
I think that's a useful feature, we should maintain it in Plomino 2.

**Comment by ivanteoh** [comment]
https://github.com/plomino/Plomino/pull/826 is the pull request for this fix.
