### ISSUE TITLE
Filtering Date ranges in Plomino Views dynamically

### ISSUE THREAD

**Issue by AshRaghav** [plomino/Plomino#833]
Hi,

Is it possible to filter by Date Ranges on specific columns in a Plomino view dynamically?

I did try looking into the DataTables filtering plugin but it requires to have a separate Date range filter field set outside the view and I am unsure if that'll really work. So I have stopped fiddling with it, in order to refrain from breaking anything.

I'd really appreciate if you can kindly share any implementation examples from the past.

Thanks

**Comment by ebrehault** [comment]
With a view you can't, but you can do it with a Datagrid field in Page form.

**Comment by AshRaghav** [comment]
Thanks Eric. I think the same problem as described in my other thread is that Datagrids don't show any links to the documents that was generated. 

Hence why I am looking for the possibilities to implement the filtering with Plomino Views.
