### ISSUE TITLE
Bulk update certain fields in Plomino documents within a view

### ISSUE THREAD

**Issue by AshRaghav** [plomino/Plomino#837]
Hi @ebrehault @jean 

Is there a way to select a set of plomino documents and choose a particular field to updated? like dates or statuses? 

Sorry if this sounds like an absurd question.

Thanks

**Comment by ebrehault** [comment]
You can implement this feature with Page form.

**Comment by AshRaghav** [comment]
Thanks @ebrehault - have you got any examples of how to implement this? Ideally I am expecting to allow users to select a set of plomino documents in a view (through checkbox selection) and update any common fields across those documents.

**Comment by ebrehault** [comment]
Use a DocLink field to list the selectable documents.

**Comment by AshRaghav** [comment]
@ebrehault - thanks again. I must admit, I am not sure how it works but having said that, I'll give your suggestions a try and will come back if I have any questions.
