### ISSUE TITLE
Refresh db or what else?

### ISSUE THREAD

**Issue by ermancio** [plomino/Plomino#843]
Hi.
I have a view column that shows dates if they are >= now where now = DateTime().
When I save the document, dates are shown correctly at that time.
When the date passed (< now), I need to save the document again (or refresh db) to hide it in the column.

Do you have any solution?
Luca

**Comment by djay** [comment]
Views always as a boolean field index saved at document save. so your idea won’t work.

The best way to implement this I think is to write a custom view catalog search formula.

**Comment by ermancio** [comment]
Ok. Do you think it could be possible to add an action for refreshing database and re-computing documents?

**Comment by ermancio** [comment]
@djay  Could you suggest me how to do it?

**Comment by djay** [comment]
@ermancio I'm not sure. There isn't a search formula on a view, just on a search form. There really needs to be a new formula put into a column to return a catalog criteria so it can handle dynamic filtering like that.
@ebrehault

**Comment by ebrehault** [comment]
I would suggest to replace the view with a Page form containing a computed for display datagrid showing the wanted documents.

**Comment by ermancio** [comment]
Thank you very much!
