### ISSUE TITLE
Feeding view into a datagrid field

### ISSUE THREAD

**Issue by AshRaghav** [plomino/Plomino#845]
Hi @jean and @ebrehault,

I remember you were saying something along the lines of feeding a view data into a datagrid field. 

I tried doing this and it is coming up quite weirdly. It was a title of a subject and ended up showing one character per column instead of showing the complete title in one column. 

I am clearly missing something here but not able to figure it out quite. 

Can you provide some guidance please?

Thanks in Advance

**Comment by ebrehault** [comment]
I guess your formula is returning a list of strings instead of a list of list of strings.

**Comment by AshRaghav** [comment]
Thanks @ebrehault - done some more trial and error with list of lists and eventually one of the combinations worked. Probably not in the right frame of mind.

Slightly different question - the code I used in "How to calculate field content" formula for columns to be shown from the view is directly visible when I view page source. Just concerned that it might be become an opportunity to know some of the key fields of the plomino database and may result in hacking/tampering. Anyway this can be prevented?

Thanks again.

**Comment by ebrehault** [comment]
Normally only users having the PlominoManager or PlominoDesigner role can see that.

**Comment by AshRaghav** [comment]
@ebrehault - great stuff, thank you for clarifying!

I cannot believe that we are finally able to search a database with accurate results for the keywords typed in the search bar. 

No disrespect to Full-text search but because users are searching only by the titles they see on the grid, it made a lot of sense to show results relevant for what they typed.
