### ISSUE TITLE
Extracting year from a date field

### ISSUE THREAD

**Issue by ermancio** [plomino/Plomino#846]
Hi all,
I need to compare two years from two different date field for a Plomino document.
I need to show (in Plomino views) documents where 
year from a date field (1) is <== year from a date field (2)

So I need to extract the year (%Y) from the date field.
Any hint?
Thank you

**Comment by ebrehault** [comment]
`doc.my_date.year()` should work

**Comment by ebrehault** [comment]
just make the filed Computed on Save

**Comment by ermancio** [comment]
if plominoContext.isEditDocument():
   plominoContext.setItem('YEAR', plominoDocument.my_date.year())

Right?

**Comment by ermancio** [comment]
Another question:
I need it only on editDocument....

**Comment by ermancio** [comment]
Because my_date must be valued only on edit and not on create.
So on the first save, I'll have no values for my_date field

**Comment by ermancio** [comment]
I wrote

if plominoContext.isEditMode():
   context.my_date.year()

No more errors but NoneType on YEAR

**Comment by ermancio** [comment]
Done!
Thank you
