### ISSUE TITLE
Data from documents available for different database

### ISSUE THREAD

**Issue by lucamancini** [plomino/Plomino#852]
Hi,
I'd like to develop a new application (not using Plone/Plomino) based on data from plomino document.
I need to make them available to the new database (still to be defined) run-time or by means a cron ora a scheduled procedure.
In other words user should be able to read and select data from Plomino documents in order to use them.
Any hint?
Thank you

**Comment by ebrehault** [comment]
2 options I think:
- use the JSOn endpoint for a view containing all your docs
- implement a PlominoAgent taking some criteria and returning the matching documents serialized in JSON

**Comment by lucamancini** [comment]
Ok.
I'm using Plone 4.3 with Plomino 1.15.1
And unfortunately I cannot update...

**Comment by ebrehault** [comment]
You still can create an agent to emit the data.

**Comment by lucamancini** [comment]
I did ti using the Json endpoint for a view containing all your docs.
Thank you!
