### ISSUE TITLE
date/time field for 2021...

### ISSUE THREAD

**Issue by lucamancini** [plomino/Plomino#859]
Hi all,
when I save a document containing a date/time field with a date in 2021 (i.e. 2021/01/14), Plomino saves correctly but when I edit the document, the calendar shows **2020/12/31**.
Saving again, the date remains correct.

For 2020 and past, everything is correct.

Date settings for Plomino database are %d-%m-%Y.

Could you help me?

**Comment by ebrehault** [comment]
do you have the same behavior the 2 datetime field rendering options (JQuery and default)?

**Comment by lucamancini** [comment]
My date in the document is 2021-01-30.
This is what I see when edit the document
![Immagine 2021-01-07 180731](https://user-images.githubusercontent.com/6359740/103921850-43e14f80-5113-11eb-906a-c18ea12bac3f.png)
Analyzing the page the date is right
![Immagine 2021-01-07 180714](https://user-images.githubusercontent.com/6359740/103921956-670bff00-5113-11eb-8f0d-281a17132368.png)

**Comment by lucamancini** [comment]
In the document properties we have the following
![Immagine 2021-01-07 182355](https://user-images.githubusercontent.com/6359740/103923416-61171d80-5115-11eb-9eb1-ed93e50e0b4c.png)

This behaviour happens to all the date/time fields since january 1st

**Comment by ebrehault** [comment]
ok so you're using the JS widget
Does it work if you switch to the default widget rendering?

**Comment by ermancio** [comment]
Please suggest me how to switch

**Comment by ebrehault** [comment]
I do not remember well but if you edit the date field, there is a settings tab or something and you can pick a different rendering widget.

**Comment by lucamancini** [comment]
I tried to work on the settings of the date field.
These are the available settings

![Immagine 2021-01-08 102236](https://user-images.githubusercontent.com/6359740/103997131-00322880-519b-11eb-8128-91c6becbcd9e.png)

It doesn't work.

It's a very strange thing that for every date in 2021, the field shows 2020/12/31 during editing...
It seems to be a date limit....

Maybe we can try to set some settings in portal_properties/site_properties?

![Immagine 2021-01-08 102952](https://user-images.githubusercontent.com/6359740/103998046-fe1c9980-519b-11eb-8914-9ab827515424.png)

**Comment by ebrehault** [comment]
ok maybe it is not in settings but in the main field property, but there is definitely a way to change the widget

**Comment by lucamancini** [comment]
Please, Eric, could you help me to know how?

**Comment by ebrehault** [comment]
I really do not remember well enough

could you screenshot the field edit page?

**Comment by lucamancini** [comment]
![Immagine 2021-01-08 123557](https://user-images.githubusercontent.com/6359740/104010962-a38c3900-51ad-11eb-897a-c689618bfaef.png)

**Comment by lucamancini** [comment]
This is the visualization mode for 2021 date

![Immagine 2021-01-08 123807](https://user-images.githubusercontent.com/6359740/104011190-0382df80-51ae-11eb-9efb-8897cdc1248d.png)

and this is in edit mode

![Immagine 2021-01-08 123837](https://user-images.githubusercontent.com/6359740/104011231-0f6ea180-51ae-11eb-97d1-b843149f7517.png)

For a document with a date in 2020 I have

![Immagine 2021-01-08 124102](https://user-images.githubusercontent.com/6359740/104011404-552b6a00-51ae-11eb-9cb9-f98e106f9f2e.png)

and

![Immagine 2021-01-08 124122](https://user-images.githubusercontent.com/6359740/104011416-59f01e00-51ae-11eb-8496-ca3e41aeeca5.png)

**Comment by ebrehault** [comment]
So when you are on the Default edit page you've screenshotted, if you click on the Settings tab, don't you see a parameter named "Field rendering"?

**Comment by fulv** [comment]
I've seen some github issues floating around in the last few days that
might be related.  Apparently, there is some ArcheTypes code that sets the
upper limit for date fields to Dec 31, 2020.
-- 
Fulvio

**Comment by ebrehault** [comment]
ok, so a new flavour of Y2K bug

Sorry @lucamancini, if that's the case, it means it probably won't be fixed (Archetypes is not maintained anymore, so the only way is to fix Plomino so it does not use the Archetypes code anymore when managing dates).

**Comment by fulv** [comment]
The Archetypes issue might be a red herring, I don't know.  Perhaps it only
affects older versions of Archetypes.  But if that is the problem, then a
monkeypatch could fix it.
-- 
Fulvio

**Comment by lucamancini** [comment]
Ok Fulvio.
Unfortunately I'm not a programmer.
Any hint for me?
Is there a way out?

**Comment by lucamancini** [comment]
[https://github.com/plone/Products.Archetypes/issues/133]

**Comment by lucamancini** [comment]
I fixed it!
In
products.cmfplone-4.2.0.1-py2.6.egg\Products\CMFPlone\skins\plone_scripts/date_components_support.py`
and
plone.app.form-2.1-py2.6.egg\plone\app\form\widgets/datecomponents.py

you need to modify PLONE_CEILING=DateTime(2021,0) # 2020-12-31 in PLONE_CEILING = DateTime(**2500**, 0) # 24**99**-12-31

Now my 12-year old son will sleep soundly...

**Comment by ebrehault** [comment]
ahahaha!!!!!!!!!!!! that's great! congrats!
I love the messages sequence:

> Unfortunately I'm not a programmer

same guy, 1 hour later:

> In
products.cmfplone-4.2.0.1-py2.6.egg\Products\CMFPlone\skins\plone_scripts/date_components_support.py`
and
plone.app.form-2.1-py2.6.egg\plone\app\form\widgets/datecomponents.py
> you need to modify PLONE_CEILING=DateTime(2021,0) # 2020-12-31 in PLONE_CEILING = DateTime(2500, 0) # 2499-12-31

Maybe you are not a programmer, but you must be the not-a-programmer-with-very-good-programming-skills type then :)

**Comment by lucamancini** [comment]
Thank you Eric!
See you soon
